export const agentMasterInitialValue = {
  id: "",
  BussinessType: "",
  WebsiteUrl: "",
  SalesPerson: "",
  OperationsPerson: "",
  CompanyName: "",
  CompanyType: "",
  Consortia: "",
  ISO: "",
  CompanyPhoneNumber: "",
  CompanyEmailAddress: "",
  Competitor: "",
  MarketType: "",
  LocalAgent: "Yes",
  Nationality: "",
  Country: "",
  Category: "",
  TourType: "",
  PreferredLanguage: "",
  Status: "1",
  AddedBy: 1,
  UpdatedBy: 0,
};

export const directClientInitialValue = {
  ContactType: "",
  Nationality: "",
  Title: "",
  FirstName: "",
  MiddleName: "",
  LastName: "",
  Gender: "",
  DOB: "",
  AnniversaryDate: "",
  HolidayPreference: [],
  Country: "",
  State: "",
  City: "",
  Pin_Zip: "",
  Address: "",
  Facebook: "",
  Twitter: "",
  LinkedIn: "",
  Instagram: "",
  Skype: "",
  MSN_Id: "",
  Remark1: "",
  Remark2: "",
  Remark3: "",
  SalesPerson: "",
  Status: "",
  FamilyCode: "",
  FamilyRelation: "",
  MealPreference: "",
  SpecialAssisteance: "",
  SeatPreference: "",
  AccomodationPreference: "",
  MarketType: "",
  CovidVaccinated: "",
  NewsLetter: "",
  EmergencyContactName: "",
  Relation: "",
  EmergencyContactNumber: "",
  AddedBy: "1",
};

export const directClientContact = {
  Contact_Type: "",
  CountryCode: "",
  Mobile: "",
  EmailType: "",
  Email: "",
};

export const directClientDocumentation = {
  DocumentType: "",
  DocumentRequired: "",
  DocumentNo: "",
  IssueDate: "",
  ExpiryDate: "",
  IssueCountry: "",
  DocumentTitle: "",
  ImageData: "",
};

export const agentBankDetailsInitialValue = {
  id: "",
  Type: "Agent",
  Fk_partnerid: 3,
  BankName: "",
  BankBranch: "",
  AccountNumber: "",
  IfscCode: "",
  PhoneNumber: "",
  EmailId: "",
  SwiftCode: "",
  Address: "",
  CheckToDefault: "Yes",
  BenificiryName: "",
  Status: "Yes",
  AddedBy: 1,
  UpdatedBy: 0,
};
