export const agentMasterInitialValue = {
  BussinessType: "",
  WebsiteUrl: "",
  SalesPerson: "",
  OperationsPerson: "",
  CompanyName: "",
  CompanyType: "",
  Consortia: "",
  ISO: "",
  CompanyPhoneNumber: "",
  CompanyEmailAddress: "",
  Competitor: "",
  MarketType: "",
  LocalAgent: "Yes",
  Nationality: "",
  Country: "",
  Category: "",
  TourType: "",
  PreferredLanguage: "",
  AgentInfo: "",
  Remarks: "",
  Status: "1",
  AddedBy: 1,
  UpdatedBy: 0,
};

export const directClientInitialValue = {
  ContactType: "",
  Nationality: "",
  Title: "",
  FirstName: "",
  MiddleName: "",
  LastName: "",
  Gender: "",
  DOB: "",
  AnniversaryDate: "",
  HolidayPreference: [],
  Country: "",
  State: "",
  City: "",
  Pin_Zip: "",
  Address: "",
  Facebook: "",
  Twitter: "",
  LinkedIn: "",
  Instagram: "",
  Skype: "",
  MSN_Id: "",
  Remark1: "",
  Remark2: "",
  Remark3: "",
  SalesPerson: "",
  Status: "",
  FamilyCode: "",
  FamilyRelation: "",
  MealPreference: "",
  SpecialAssisteance: "",
  SeatPreference: "",
  AccomodationPreference: "",
  MarketType: "",
  CovidVaccinated: "",
  NewsLetter: "",
  EmergencyContactName: "",
  Relation: "",
  EmergencyContactNumber: "",
  AddedBy: "1",
};

export const directClientContact = {
  Contact_Type: "",
  CountryCode: "",
  Mobile: "",
  EmailType: "",
  Email: "",
};

export const directClientDocumentation = {
  DocumentType: "",
  DocumentRequired: "",
  DocumentNo: "",
  IssueDate: "",
  ExpiryDate: "",
  IssueCountry: "",
  DocumentTitle: "",
  ImageData: "",
  ImageName: "",
};

export const agentBankDetailsInitialValue = {
  id: "",
  Type: "",
  Fk_partnerid: "",
  BankName: "",
  BankBranch: "",
  AccountNumber: "",
  IfscCode: "",
  PhoneNumber: "",
  EmailId: "",
  SwiftCode: "",
  Address: "",
  CheckToDefault: "Yes",
  BenificiryName: "",
  Status: "Yes",
  AddedBy: 1,
  UpdatedBy: 0,
};

export const agentAddCallInitialValue = {
  id: "",
  Type: "",
  Fk_partnerid: "",
  Fk_Leadsource: "",
  BusinessType: "",
  AgentName: "",
  AgentId: "",
  AgentContactPersonId: "",
  AgentContactPerson: "",
  EmailId: "",
  CountryId: "",
  Destination: [],
  SalesPerson: "",
  MobileNumber: "",
  ContactNumber: "",
  Startdate: "",
  StartTime: "",
  CallDuration: "",
  EndTime: "",
  NextFollowUpdate: "",
  NextFollowUpTime: "",
  ReminderTime: "",
  CallType: "",
  Campaign: "",
  CallAgenda: "",
  Description: "",
  CallStatus: "",
  Status: "Yes",
  AddedBy: "1",
  UpdatedBy: "0",
};

export const meetingAddIntitalValue = {
  id: "",
  Type: "",
  Fk_partnerid: "",
  Fk_Leadsource: "",
  BusinessType: "",
  AgentName: "",
  AgentId: "",
  AgentContactPersonId: "",
  AgentContactPerson: "",
  EmailId: "",
  CountryId: "",
  Destination: "",
  SalesPerson: "",
  MobileNumber: "",
  ContactNumber: "",
  Startdate: "",
  StartTime: "",
  CallDuration: "",
  EndTime: "",
  NextFollowUpdate: "",
  NextFollowUpTime: "",
  ReminderTime: "",
  MeetingOutcome: "",
  Campaign: "",
  MeetingAgenda: "",
  Description: "",
  Status: "1",
  AddedBy: "1",
  UpdatedBy: "0",
};

export const addTaskInitialValue = {
  id: "",
  Type: "",
  Fk_partnerid: "",
  Fk_Leadsource: "",
  BusinessType: "",
  AgentName: "",
  AgentId: "",
  AgentContactPersonId: "",
  AgentContactPerson: "",
  EmailId: "",
  CountryId: "",
  Destination: "",
  SalesPerson: "",
  MobileNumber: "",
  ContactNumber: "",
  Startdate: "",
  StartTime: "",
  CallDuration: "",
  EndTime: "",
  NextFollowUpdate: "",
  NextFollowUpTime: "",
  ReminderTime: "",
  Priority: "",
  TaskSubject: "",
  Description: "",
  Status: "Yes",
  AddedBy: "1",
  UpdatedBy: "0",
};

export const addOfficeInitialValue = {
  id: "",
  Name: "",
  Type: "",
  Fk_partnerid: "",
  Country: "",
  State: "",
  City: "",
  Address: "",
  PinCode: "",
  Pan: "",
  Gstn: "",
  PrimaryAddress: "",
  PlaceOfDeliveryInvoice: "",
  AddedBy: "1",
  UpdatedBy: 0,
};

export const companyDocumentsInitialValue = {
  id: "",
  Type: "",
  Fk_partnerid: "",
  DocumentName: "",
  DocumentNumber: "",
  IssueDate: "",
  ExpireDate: "",
  Remarks: "",
  DocumentImageName: "",
  DocumentImageData: "",
  Status: "Yes",
  AddedBy: 1,
  UpdatedBy: 0,
};

export const addContactInitialValue = {
  id: "",
  ParentId: "",
  OfficeName: "",
  Title: "",
  MetDuring: "",
  FirstName: "",
  LastName: "",
  Division: "1",
  Designation: "",
  Newsletter: "Yes",
  CountryCode: "",
  Phone: "",
  MobileNo: "",
  Email: "",
  AlternateEmail: "",
  DateOfBirth: "",
  AnniversaryDate: "",
  SkypeId: "",
  MsnId: "",
  FacebookProfile: "",
  LinkedInProfile: "",
  TwitterProfile: "",
  InstagramProfile: "",
  ImageNameOne: "",
  ImageOneData: "",
  ImageNameTwo: "",
  ImageTwoData: "",
  ImageNameThree: "",
  ImageThreeData: "",
  Status: "Yes",
  AddedBy: "1",
  UpdatedBy: "1",
};
