export const queryInitial = {
  id: "",
  CompanyId: "",
  ClientType: "",
  PackageCode: "",
  PackageName: "",
  BusinessType: "",
  QueryId: "",
  TourId: "",
  LeadPax: "",
  Subject: "",
  QueryType: "",
  Priority: "",
  TravelInfo: "",
  TAT: "",
  TatName: "",
  LeadSource: "",
  FromDate: "",
  ToDate: "",
  MealPlan: "",
  PackageId: "",
  ImmediateOccupancy: "",
  Nationality: "",
  MarketType: "",
  FDCode: "",
  AgentId: "",
  AssignUser: "",
  AddEmail: "",
  AdditionalInfo: "",
};

export const travelInitial = {
  Type: "1",
  FromDate: "",
  ToDate: "",
  TotalNights: "",
  SeasonType: "",
  SeasonYear: "",
};

export const paxInitial = {
  Adult: "1",
  Child: "",
  Infant: "",
};

export const roomInitial = {
  SGLRoom: 1,
  DBLRoom: "",
  TPLRoom: "",
  TWINRoom: "",
  ExtraBed: "",
};

export const valueAddInitial = {
  Flight: "NO",
  Visa: "NO",
  Insurance: "NO",
  Train: "NO",
  Transfer: "NO",
};

export const suggestedPackageData = [
  {
    Id: "",
    PackageId: "1",
    QueryId: "",
    PackageImage:
      "https://media.cntraveller.com/photos/617936a2a8f76267fba5d115/master/w_1600%2Cc_limit/The%2520Burj%2520Khalifa-GettyImages-1084264582.jpeg",
    FDCode: "321",
    PackageCode: "431",
    PackageName: "6 Days Dubai Package",
    ClientType: "2",
    AgentId: "2",
    LeadPax: "Ansar",
    Subject: "its subject field required",
    AddEmail: "ansar@gmail.com, sanaul@gmail.com",
    AdditionalInfo: "itsdefaultinfo",
    QueryType: "2",
    Priority: "1",
    TAT: "23",
    TourType: "2",
    LeadSource: "3",
    LeadRefrencedId: "#87766565",
    HotelPrefrence: "3",
    HotelType: "3",
    MealPlan: "3",
    TravelInfo: "1",
    ValueAddedServices: [
      {
        Flight: "NO",
        Visa: "NO",
        Insurance: "NO",
        Train: "NO",
        Transfer: "NO",
      },
    ],

    TravelDate: [
      {
        Type: "1",
        FromDate: "2024-05-23",
        ToDate: "",
        TotalNights: "2",
        SeasonType: "1",
        SeasonYear: "2",
      },
    ],
    PaxType: "1",
    PaxInfo: [
      {
        Adult: "3",
        Child: "1",
        Infant: "1",
      },
    ],
    RoomInfo: [
      {
        Room: "1",
        Single: "1",
        Double: "",
        Twin: "",
        Triple: "",
        ExtraBed: "",
      },
    ],
    AddedBy: "1",
    UpdatedBy: "0",
  },
  {
    Id: "",
    PackageId: "2",
    QueryId: "1",
    PackageImage:
      "https://i.natgeofe.com/n/483e77f7-f52b-432a-a0f5-d9cd1489a95a/madinat-jumeirah-dubai-uae_3x4.jpg",
    FDCode: "321",
    PackageCode: "431",
    PackageName: "4 Days Maldives Package",
    ClientType: "3",
    AgentId: "2",
    LeadPax: "Sanif",
    Subject: "its subject field required",
    AddEmail: "ansar@gmail.com, sanaul@gmail.com",
    AdditionalInfo: "itsdefaultinfo",
    QueryType: "2",
    Priority: "1",
    TAT: "23",
    TourType: "2",
    LeadSource: "3",
    LeadReferencedId: "#87766565",
    HotelPreference: "3",
    VehiclePrefrence: "1",
    HotelType: "3",
    MealPlan: "3",
    TravelInfo: "1",
    ValueAddedServices: [
      {
        Flight: "NO",
        Visa: "NO",
        Insurance: "NO",
        Train: "NO",
        Transfer: "NO",
      },
    ],
    TravelDate: [
      {
        Type: "1",
        FromDate: "2024-05-13",
        ToDate: "",
        TotalNights: "1",
        SeasonType: "1",
        SeasonYear: "2",
      },
    ],
    PaxType: "1",
    PaxInfo: [
      {
        Adult: "3",
        Child: "1",
        Infant: "1",
      },
    ],
    RoomInfo: [
      {
        Room: "1",
        Single: "1",
        Double: "",
        Twin: "",
        Triple: "",
        ExtraBed: "",
      },
    ],
    SalesPerson: "Ansar",
    AssignUser: "User-1",
    ContractPerson: "Rizwan",
    AddedBy: "1",
    UpdatedBy: "0",
  },
  {
    Id: "",
    PackageId: "3",
    QueryId: "1",
    PackageImage:
      "https://cf.bstatic.com/xdata/images/hotel/max1024x768/377486240.jpg?k=956825fb96b0ccd1d754e9b01d3f8fa33d83eb47c44b171bee406d9ae7b78c5e&o=&hp=1",
    FDCode: "321",
    PackageCode: "431",
    PackageName: "8 Days Goa Package",
    ClientType: "4",
    AgentId: "2",
    LeadPax: "Nishank",
    Subject: "its subject field required",
    AddEmail: "ansar@gmail.com, sanaul@gmail.com",
    AdditionalInfo: "itsdefaultinfo",
    QueryType: "2",
    Priority: "1",
    TAT: "23",
    TourType: "2",
    LeadSource: "3",
    LeadReferencedId: "#87766565",
    HotelPreference: "3",
    VehiclePrefrence: "1",
    HotelType: "3",
    MealPlan: "3",
    TravelInfo: "1",
    ValueAddedServices: [
      {
        Flight: "NO",
        Visa: "NO",
        Insurance: "NO",
        Train: "NO",
        Transfer: "NO",
      },
    ],

    TravelDate: [
      {
        Type: "1",
        FromDate: "2024-05-09",
        ToDate: "",
        TotalNights: "5",
        SeasonType: "1",
        SeasonYear: "2",
      },
    ],
    PaxType: "1",
    PaxInfo: [
      {
        Adult: "3",
        Child: "1",
        Infant: "1",
      },
    ],
    RoomInfo: [
      {
        Room: "1",
        Single: "1",
        Double: "",
        Twin: "",
        Triple: "",
        ExtraBed: "",
      },
    ],
    SalesPerson: "Ansar",
    AssignUser: "User-1",
    ContractPerson: "Rizwan",
    AddedBy: "1",
    UpdatedBy: "0",
  },
  {
    Id: "",
    PackageId: "4",
    QueryId: "1",
    PackageImage:
      "https://r1imghtlak.mmtcdn.com/a271073a79ca11eca91e0a58a9feac02.jpg?&output-quality=75&downsize=520:350&crop=520:350;2,0&output-format=jpg&downsize=192:224.4&crop=192:224.4",
    FDCode: "321",
    PackageCode: "431",
    PackageName: "Weekend Thailand Package",
    ClientType: "5",
    AgentId: "2",
    LeadPax: "Rizwan",
    Subject: "its subject field required",
    AddEmail: "ansar@gmail.com, sanaul@gmail.com",
    AdditionalInfo: "itsdefaultinfo",
    QueryType: "2",
    Priority: "1",
    TAT: "23",
    TourType: "2",
    LeadSource: "3",
    LeadReferencedId: "#87766565",
    HotelPreference: "3",
    VehiclePrefrence: "1",
    HotelType: "3",
    MealPlan: "3",
    TravelInfo: "1",
    ValueAddedServices: [
      {
        Flight: "NO",
        Visa: "NO",
        Insurance: "NO",
        Train: "NO",
        Transfer: "NO",
      },
    ],

    TravelDate: [
      {
        Type: "1",
        FromDate: "2024-05-05",
        ToDate: "",
        TotalNights: "2",
        SeasonType: "1",
        SeasonYear: "2",
      },
    ],
    PaxType: "1",
    PaxInfo: [
      {
        Adult: "3",
        Child: "1",
        Infant: "1",
      },
    ],
    RoomInfo: [
      {
        Room: "1",
        Single: "1",
        Double: "",
        Twin: "",
        Triple: "",
        ExtraBed: "",
      },
    ],
    SalesPerson: "Ansar",
    AssignUser: "User-1",
    ContractPerson: "Rizwan",
    AddedBy: "1",
    UpdatedBy: "0",
  },
  {
    Id: "",
    PackageId: "5",
    QueryId: "1",
    PackageImage:
      "https://static.dezeen.com/uploads/2022/02/museum-of-the-future-killa-design-dubai_dezeen_2364_col_20-scaled.jpg",
    FDCode: "321",
    PackageCode: "431",
    PackageName: "WeekDays Kashmir Package",
    ClientType: "5",
    AgentId: "2",
    LeadPax: "Ansar",
    Subject: "its subject field required",
    AddEmail: "ansar@gmail.com, sanaul@gmail.com",
    AdditionalInfo: "itsdefaultinfo",
    QueryType: "2",
    Priority: "1",
    TAT: "23",
    TourType: "2",
    LeadSource: "3",
    LeadReferencedId: "#87766565",
    HotelPreference: "3",
    VehiclePrefrence: "1",
    HotelType: "3",
    MealPlan: "3",
    TravelInfo: "1",
    ValueAddedServices: [
      {
        Flight: "NO",
        Visa: "NO",
        Insurance: "NO",
        Train: "NO",
        Transfer: "NO",
      },
    ],

    TravelDate: [
      {
        Type: "1",
        FromDate: "2024-05-10",
        ToDate: "",
        TotalNights: "6",
        SeasonType: "1",
        SeasonYear: "2",
      },
    ],
    PaxType: "1",
    PaxInfo: [
      {
        Adult: "3",
        Child: "1",
        Infant: "1",
      },
    ],
    RoomInfo: [
      {
        Room: "1",
        Single: "1",
        Double: "",
        Twin: "",
        Triple: "",
        ExtraBed: "",
      },
    ],
    SalesPerson: "Ansar",
    AssignUser: "User-1",
    ContractPerson: "Rizwan",
    AddedBy: "1",
    UpdatedBy: "0",
  },
  {
    Id: "",
    PackageId: "6",
    QueryId: "1",
    PackageImage:
      "https://akm-img-a-in.tosshub.com/sites/visualstory/stories/2021_06/story_1330/assets/46.jpeg?time=1624977644&size=*:900",
    FDCode: "321",
    PackageCode: "431",
    PackageName: "Full Manali Package",
    ClientType: "3",
    AgentId: "2",
    LeadPax: "Ansar",
    Subject: "its subject field required",
    AddEmail: "ansar@gmail.com, sanaul@gmail.com",
    AdditionalInfo: "itsdefaultinfo",
    QueryType: "2",
    Priority: "1",
    TAT: "23",
    TourType: "1",
    LeadSource: "3",
    LeadReferencedId: "#87766565",
    HotelPreference: "3",
    VehiclePrefrence: "1",
    HotelType: "3",
    MealPlan: "3",
    TravelInfo: "1",
    ValueAddedServices: [
      {
        Flight: "NO",
        Visa: "NO",
        Insurance: "NO",
        Train: "NO",
        Transfer: "NO",
      },
    ],

    TravelDate: [
      {
        Type: "1",
        FromDate: "2024-05-19",
        ToDate: "",
        TotalNights: "1",
        SeasonType: "1",
        SeasonYear: "2",
      },
    ],
    PaxType: "1",
    PaxInfo: [
      {
        Adult: "3",
        Child: "1",
        Infant: "1",
      },
    ],
    RoomInfo: [
      {
        Room: "1",
        Single: "1",
        Double: "",
        Twin: "",
        Triple: "",
        ExtraBed: "",
      },
    ],
    SalesPerson: "Ansar",
    AssignUser: "User-1",
    ContractPerson: "Rizwan",
    AddedBy: "1",
    UpdatedBy: "0",
  },
  {
    Id: "",
    PackageId: "7",
    QueryId: "1",
    PackageImage:
      "https://media.architecturaldigest.com/photos/6032b3c9a0b9bd2edd5510d1/1:1/w_2880,h_2880,c_limit/Hero_Soneva%20Jani%20Chapter%20Two%20by%20Aksham%20Abdul%20Ghadir.jpg",
    FDCode: "321",
    PackageCode: "431",
    PackageName: "Mumbai Ship Arena Package",
    ClientType: "1",
    AgentId: "2",
    LeadPax: "Ansar",
    Subject: "its subject field required",
    AddEmail: "ansar@gmail.com, sanaul@gmail.com",
    AdditionalInfo: "itsdefaultinfo",
    QueryType: "2",
    Priority: "1",
    TAT: "23",
    TourType: "2",
    LeadSource: "3",
    LeadReferencedId: "#87766565",
    HotelPreference: "3",
    VehiclePrefrence: "1",
    HotelType: "3",
    MealPlan: "3",
    TravelInfo: "1",
    ValueAddedServices: [
      {
        Flight: "NO",
        Visa: "NO",
        Insurance: "NO",
        Train: "NO",
        Transfer: "NO",
      },
    ],

    TravelDate: [
      {
        Type: "1",
        FromDate: "2024-05-15",
        ToDate: "",
        TotalNights: "1",
        SeasonType: "1",
        SeasonYear: "2",
      },
    ],
    PaxType: "1",
    PaxInfo: [
      {
        Adult: "3",
        Child: "1",
        Infant: "1",
      },
    ],
    RoomInfo: [
      {
        Room: "1",
        Single: "1",
        Double: "",
        Twin: "",
        Triple: "",
        ExtraBed: "",
      },
    ],
    SalesPerson: "Ansar",
    AssignUser: "User-1",
    ContractPerson: "Rizwan",
    AddedBy: "1",
    UpdatedBy: "0",
  },
  {
    Id: "",
    PackageId: "8",
    QueryId: "1",
    PackageImage:
      "https://assets.vogue.in/photos/63889b741b8712b28236a56b/2:3/w_2560%2Cc_limit/Goa.jpeg",
    FDCode: "321",
    PackageCode: "431",
    PackageName: "10 Days Qatar Package",
    ClientType: "2",
    AgentId: "2",
    LeadPax: "Ansar",
    Subject: "its subject field required",
    AddEmail: "ansar@gmail.com, sanaul@gmail.com",
    AdditionalInfo: "itsdefaultinfo",
    QueryType: "2",
    Priority: "1",
    TAT: "23",
    TourType: "2",
    LeadSource: "3",
    LeadReferencedId: "#87766565",
    HotelPreference: "3",
    VehiclePrefrence: "1",
    HotelType: "3",
    MealPlan: "3",
    TravelInfo: "1",
    ValueAddedServices: [
      {
        Flight: "NO",
        Visa: "NO",
        Insurance: "NO",
        Train: "NO",
        Transfer: "NO",
      },
    ],

    TravelDate: [
      {
        Type: "1",
        FromDate: "2024-05-02",
        ToDate: "",
        TotalNights: "3",
        SeasonType: "1",
        SeasonYear: "2",
      },
    ],
    PaxType: "1",
    PaxInfo: [
      {
        Adult: "3",
        Child: "1",
        Infant: "1",
      },
    ],
    RoomInfo: [
      {
        Room: "1",
        Single: "1",
        Double: "",
        Twin: "",
        Triple: "",
        ExtraBed: "",
      },
    ],
    SalesPerson: "Ansar",
    AssignUser: "User-1",
    ContractPerson: "Rizwan",
    AddedBy: "1",
    UpdatedBy: "0",
  },
];

export const roomListStaticApi = [
  {
    Name: "SGLRoom",
  },
  {
    Name: "DBLRoom",
  },
  {
    Name: "TPLRoom",
  },
  {
    Name: "TWINRoom",
  },
  {
    Name: "ExtraBed(A)",
  },
];
