export const queryInitial = {
  id: "",
  CompanyId: "",
  ClientType: "",
  PackageCode: "",
  PackageName: "",
  BusinessType: "",
  QueryId: "",
  TourId: "",
  LeadPax: "",
  Subject: "",
  QueryType: "",
  Priority: "",
  TravelInfo: "",
  TAT: "",
  TatName: "",
  LeadSource: "",
  FromDate: "",
  ToDate: "",
  MealPlan: "",
  PackageId: "",
  ImmediateOccupancy: "",
  Nationality: "",
  MarketType: "",
  FDCode: "",
  AgentId: "",
  AssignUser: "",
  AddEmail: "",
  AdditionalInfo: "",
};

export const travelInitial = {
  Type: "1",
  FromDate: "",
  ToDate: "",
  TotalNights: "",
  SeasonType: "",
  SeasonYear: "",
};

export const paxInitial = {
  Adult: "1",
  Child: "",
  Infant: "",
};

export const roomInitial = {
  SGLRoom: 1,
  DBLRoom: "",
  TPLRoom: "",
  TWINRoom: "",
  ExtraBed: "",
};

export const valueAddInitial = {
  Flight: "NO",
  Visa: "NO",
  Insurance: "NO",
  Train: "NO",
  Transfer: "NO",
};

export const suggestedPackageData = [
  {
    Id: "",
    PackageId: "1",
    QueryId: "",
    FDCode: "321",
    PackageCode: "431",
    PackageName: "Agra 2N Jaipur 1N Delhi 1N Agra 1N",
    ClientType: "2",
    AgentId: "2",
    LeadPax: "Ansar",
    Subject: "its subject field required",
    AddEmail: "ansar@gmail.com, sanaul@gmail.com",
    AdditionalInfo: "itsdefaultinfo",
    QueryType: "2",
    Priority: "1",
    TAT: "23",
    TourType: "2",
    LeadSource: "3",
    LeadRefrencedId: "#87766565",
    HotelPrefrence: "3",
    HotelType: "3",
    MealPlan: "3",
    TravelInfo: "1",
    ValueAddedServices: [
      {
        Flight: "NO",
        Visa: "NO",
        Insurance: "NO",
        Train: "NO",
        Transfer: "NO",
      },
    ],

    TravelDate: [
      {
        Type: "1",
        FromDate: "2024-05-23",
        ToDate: "",
        TotalNights: "2",
        SeasonType: "1",
        SeasonYear: "2",
      },
    ],
    PaxType: "1",
    PaxInfo: [
      {
        Adult: "3",
        Child: "1",
        Infant: "1",
      },
    ],
    RoomInfo: [
      {
        Room: "1",
        Single: "1",
        Double: "",
        Twin: "",
        Triple: "",
        ExtraBed: "",
      },
    ],
    AddedBy: "1",
    UpdatedBy: "0",
  },
  {
    Id: "",
    PackageId: "2",
    QueryId: "1",
    FDCode: "321",
    PackageCode: "431",
    PackageName: "Agra 2N Jaipur 1N",
    ClientType: "3",
    AgentId: "2",
    LeadPax: "Sanif",
    Subject: "its subject field required",
    AddEmail: "ansar@gmail.com, sanaul@gmail.com",
    AdditionalInfo: "itsdefaultinfo",
    QueryType: "2",
    Priority: "1",
    TAT: "23",
    TourType: "2",
    LeadSource: "3",
    LeadReferencedId: "#87766565",
    HotelPreference: "3",
    VehiclePrefrence: "1",
    HotelType: "3",
    MealPlan: "3",
    TravelInfo: "1",
    ValueAddedServices: [
      {
        Flight: "NO",
        Visa: "NO",
        Insurance: "NO",
        Train: "NO",
        Transfer: "NO",
      },
    ],
    TravelDate: [
      {
        Type: "1",
        FromDate: "2024-05-13",
        ToDate: "",
        TotalNights: "1",
        SeasonType: "1",
        SeasonYear: "2",
      },
    ],
    PaxType: "1",
    PaxInfo: [
      {
        Adult: "3",
        Child: "1",
        Infant: "1",
      },
    ],
    RoomInfo: [
      {
        Room: "1",
        Single: "1",
        Double: "",
        Twin: "",
        Triple: "",
        ExtraBed: "",
      },
    ],
    SalesPerson: "Ansar",
    AssignUser: "User-1",
    ContractPerson: "Rizwan",
    AddedBy: "1",
    UpdatedBy: "0",
  },
  {
    Id: "",
    PackageId: "3",
    QueryId: "1",
     FDCode: "321",
    PackageCode: "431",
    PackageName: "Dubai 2N Abu Dhabi 3N",
    ClientType: "4",
    AgentId: "2",
    LeadPax: "Nishank",
    Subject: "its subject field required",
    AddEmail: "ansar@gmail.com, sanaul@gmail.com",
    AdditionalInfo: "itsdefaultinfo",
    QueryType: "2",
    Priority: "1",
    TAT: "23",
    TourType: "2",
    LeadSource: "3",
    LeadReferencedId: "#87766565",
    HotelPreference: "3",
    VehiclePrefrence: "1",
    HotelType: "3",
    MealPlan: "3",
    TravelInfo: "1",
    ValueAddedServices: [
      {
        Flight: "NO",
        Visa: "NO",
        Insurance: "NO",
        Train: "NO",
        Transfer: "NO",
      },
    ],

    TravelDate: [
      {
        Type: "1",
        FromDate: "2024-05-09",
        ToDate: "",
        TotalNights: "5",
        SeasonType: "1",
        SeasonYear: "2",
      },
    ],
    PaxType: "1",
    PaxInfo: [
      {
        Adult: "3",
        Child: "1",
        Infant: "1",
      },
    ],
    RoomInfo: [
      {
        Room: "1",
        Single: "1",
        Double: "",
        Twin: "",
        Triple: "",
        ExtraBed: "",
      },
    ],
    SalesPerson: "Ansar",
    AssignUser: "User-1",
    ContractPerson: "Rizwan",
    AddedBy: "1",
    UpdatedBy: "0",
  },
  {
    Id: "",
    PackageId: "4",
    QueryId: "1",
     FDCode: "321",
    PackageCode: "431",
    PackageName: "Delhi 2N Jaipur 1N",
    ClientType: "5",
    AgentId: "2",
    LeadPax: "Rizwan",
    Subject: "its subject field required",
    AddEmail: "ansar@gmail.com, sanaul@gmail.com",
    AdditionalInfo: "itsdefaultinfo",
    QueryType: "2",
    Priority: "1",
    TAT: "23",
    TourType: "2",
    LeadSource: "3",
    LeadReferencedId: "#87766565",
    HotelPreference: "3",
    VehiclePrefrence: "1",
    HotelType: "3",
    MealPlan: "3",
    TravelInfo: "1",
    ValueAddedServices: [
      {
        Flight: "NO",
        Visa: "NO",
        Insurance: "NO",
        Train: "NO",
        Transfer: "NO",
      },
    ],

    TravelDate: [
      {
        Type: "1",
        FromDate: "2024-05-05",
        ToDate: "",
        TotalNights: "2",
        SeasonType: "1",
        SeasonYear: "2",
      },
    ],
    PaxType: "1",
    PaxInfo: [
      {
        Adult: "3",
        Child: "1",
        Infant: "1",
      },
    ],
    RoomInfo: [
      {
        Room: "1",
        Single: "1",
        Double: "",
        Twin: "",
        Triple: "",
        ExtraBed: "",
      },
    ],
    SalesPerson: "Ansar",
    AssignUser: "User-1",
    ContractPerson: "Rizwan",
    AddedBy: "1",
    UpdatedBy: "0",
  },
  {
    Id: "",
    PackageId: "5",
    QueryId: "1",
    FDCode: "321",
    PackageCode: "431",
    PackageName: "Agra 2N Jaipur 1N",
    ClientType: "5",
    AgentId: "2",
    LeadPax: "Ansar",
    Subject: "its subject field required",
    AddEmail: "ansar@gmail.com, sanaul@gmail.com",
    AdditionalInfo: "itsdefaultinfo",
    QueryType: "2",
    Priority: "1",
    TAT: "23",
    TourType: "2",
    LeadSource: "3",
    LeadReferencedId: "#87766565",
    HotelPreference: "3",
    VehiclePrefrence: "1",
    HotelType: "3",
    MealPlan: "3",
    TravelInfo: "1",
    ValueAddedServices: [
      {
        Flight: "NO",
        Visa: "NO",
        Insurance: "NO",
        Train: "NO",
        Transfer: "NO",
      },
    ],

    TravelDate: [
      {
        Type: "1",
        FromDate: "2024-05-10",
        ToDate: "",
        TotalNights: "6",
        SeasonType: "1",
        SeasonYear: "2",
      },
    ],
    PaxType: "1",
    PaxInfo: [
      {
        Adult: "3",
        Child: "1",
        Infant: "1",
      },
    ],
    RoomInfo: [
      {
        Room: "1",
        Single: "1",
        Double: "",
        Twin: "",
        Triple: "",
        ExtraBed: "",
      },
    ],
    SalesPerson: "Ansar",
    AssignUser: "User-1",
    ContractPerson: "Rizwan",
    AddedBy: "1",
    UpdatedBy: "0",
  },
  {
    Id: "",
    PackageId: "6",
    QueryId: "1",
     FDCode: "321",
    PackageCode: "431",
    PackageName: "Agra 2N Jaipur 1N",
    ClientType: "3",
    AgentId: "2",
    LeadPax: "Ansar",
    Subject: "its subject field required",
    AddEmail: "ansar@gmail.com, sanaul@gmail.com",
    AdditionalInfo: "itsdefaultinfo",
    QueryType: "2",
    Priority: "1",
    TAT: "23",
    TourType: "1",
    LeadSource: "3",
    LeadReferencedId: "#87766565",
    HotelPreference: "3",
    VehiclePrefrence: "1",
    HotelType: "3",
    MealPlan: "3",
    TravelInfo: "1",
    ValueAddedServices: [
      {
        Flight: "NO",
        Visa: "NO",
        Insurance: "NO",
        Train: "NO",
        Transfer: "NO",
      },
    ],

    TravelDate: [
      {
        Type: "1",
        FromDate: "2024-05-19",
        ToDate: "",
        TotalNights: "1",
        SeasonType: "1",
        SeasonYear: "2",
      },
    ],
    PaxType: "1",
    PaxInfo: [
      {
        Adult: "3",
        Child: "1",
        Infant: "1",
      },
    ],
    RoomInfo: [
      {
        Room: "1",
        Single: "1",
        Double: "",
        Twin: "",
        Triple: "",
        ExtraBed: "",
      },
    ],
    SalesPerson: "Ansar",
    AssignUser: "User-1",
    ContractPerson: "Rizwan",
    AddedBy: "1",
    UpdatedBy: "0",
  },
  {
    Id: "",
    PackageId: "7",
    QueryId: "1",
    FDCode: "321",
    PackageCode: "431",
    PackageName: "Agra 2N Jaipur 1N",
    ClientType: "1",
    AgentId: "2",
    LeadPax: "Ansar",
    Subject: "its subject field required",
    AddEmail: "ansar@gmail.com, sanaul@gmail.com",
    AdditionalInfo: "itsdefaultinfo",
    QueryType: "2",
    Priority: "1",
    TAT: "23",
    TourType: "2",
    LeadSource: "3",
    LeadReferencedId: "#87766565",
    HotelPreference: "3",
    VehiclePrefrence: "1",
    HotelType: "3",
    MealPlan: "3",
    TravelInfo: "1",
    ValueAddedServices: [
      {
        Flight: "NO",
        Visa: "NO",
        Insurance: "NO",
        Train: "NO",
        Transfer: "NO",
      },
    ],

    TravelDate: [
      {
        Type: "1",
        FromDate: "2024-05-15",
        ToDate: "",
        TotalNights: "1",
        SeasonType: "1",
        SeasonYear: "2",
      },
    ],
    PaxType: "1",
    PaxInfo: [
      {
        Adult: "3",
        Child: "1",
        Infant: "1",
      },
    ],
    RoomInfo: [
      {
        Room: "1",
        Single: "1",
        Double: "",
        Twin: "",
        Triple: "",
        ExtraBed: "",
      },
    ],
    SalesPerson: "Ansar",
    AssignUser: "User-1",
    ContractPerson: "Rizwan",
    AddedBy: "1",
    UpdatedBy: "0",
  },
  {
    Id: "",
    PackageId: "8",
    QueryId: "1",
     FDCode: "321",
    PackageCode: "431",
    PackageName: "Agra 2N Jaipur 1N",
    ClientType: "2",
    AgentId: "2",
    LeadPax: "Ansar",
    Subject: "its subject field required",
    AddEmail: "ansar@gmail.com, sanaul@gmail.com",
    AdditionalInfo: "itsdefaultinfo",
    QueryType: "2",
    Priority: "1",
    TAT: "23",
    TourType: "2",
    LeadSource: "3",
    LeadReferencedId: "#87766565",
    HotelPreference: "3",
    VehiclePrefrence: "1",
    HotelType: "3",
    MealPlan: "3",
    TravelInfo: "1",
    ValueAddedServices: [
      {
        Flight: "NO",
        Visa: "NO",
        Insurance: "NO",
        Train: "NO",
        Transfer: "NO",
      },
    ],

    TravelDate: [
      {
        Type: "1",
        FromDate: "2024-05-02",
        ToDate: "",
        TotalNights: "3",
        SeasonType: "1",
        SeasonYear: "2",
      },
    ],
    PaxType: "1",
    PaxInfo: [
      {
        Adult: "3",
        Child: "1",
        Infant: "1",
      },
    ],
    RoomInfo: [
      {
        Room: "1",
        Single: "1",
        Double: "",
        Twin: "",
        Triple: "",
        ExtraBed: "",
      },
    ],
    SalesPerson: "Ansar",
    AssignUser: "User-1",
    ContractPerson: "Rizwan",
    AddedBy: "1",
    UpdatedBy: "0",
  },
];

export const roomListStaticApi = [
  {
    Name: "SGLRoom",
  },
  {
    Name: "DBLRoom",
  },
  {
    Name: "TPLRoom",
  },
  {
    Name: "TWINRoom",
  },
  {
    Name: "ExtraBed(A)",
  },
];
