import ArrivalImage from "/global_assets/images/qoutation/Arrival.png";
import Departure from "/global_assets/images/qoutation/Departure1.png";
import Monument from "/global_assets/images/qoutation/monument.png";
import Hotel from "/global_assets/images/qoutation/hotel.png";
import Activity from "/global_assets/images/qoutation/activity.png";

const data = [
  {
    Name: {
      Name: "Arrival",
      Logo: ArrivalImage,
    },
    Columns: [
      {
        Label: "Flight Name/Number",
        Data: "Air-India-13989",
      },
      {
        Label: "Flight Class Name",
        Data: "First Class",
      },
      {
        Label: "Arrival Departure",
        Data: "New Delhi-Mumbai",
      },
      {
        Label: "Arrival Date Time",
        Data: "10:30",
      },
      {
        Label: "Departure Date Time",
        Data: "11:35",
      },
      {
        Label: "Adult Cost",
        Data: "INR 1500",
      },
      {
        Label: "Child Cost",
        Data: "INR 1200",
      },
    ],
  },
  {
    Name: {
      Name: "Departure",
      Logo: Departure,
    },
    Columns: [
      {
        Label: "Flight Name/Number",
        Data: "Air-India-13989",
      },
      {
        Label: "Flight Class Name",
        Data: "First Class",
      },
      {
        Label: "Arrival Departure",
        Data: "New Delhi-Mumbai",
      },
      {
        Label: "Arrival Date Time",
        Data: "10:30",
      },
      {
        Label: "Departure Date Time",
        Data: "11:35",
      },
      {
        Label: "Adult Cost",
        Data: "INR 1500",
      },
      {
        Label: "Child Cost",
        Data: "INR 1200",
      },
    ],
  },
  {
    Name: {
      Name: "Monument",
      Logo: Monument,
    },
    Columns: [
      {
        Label: "Monument Name",
        Data: "Birla Temple",
      },
      {
        Label: "Adult Cost",
        Data: "1200",
      },
      {
        Label: "Child Cost",
        Data: "1000",
      },
      {
        Label: "Start/End Time",
        Data: "10:30",
      },
    ],
  },
  {
    Name: {
      Name: "Hotel",
      Logo: Hotel,
    },
    Columns: [
      {
        Label: "Hotel Name",
        Data: "Birla Temple",
      },
      {
        Label: "Service Cost",
        Data: "1200",
      },
      {
        Label: "Meal Plan",
        Data: "1000",
      },
      {
        Label: "Tariff Type",
        Data: "10:30",
      },
    ],
  },
  {
    Name: {
      Name: "Activity",
      Logo: Activity,
    },
    Columns: [
      {
        Label: "Activity Name",
        Data: "Deep Diving",
      },
      {
        Label: "Pax Slab",
        Data: "10pax",
      },
      {
        Label: "Per Pax Cost",
        Data: "INR 1200",
      },
      {
        Label: "Arrival Date Time",
        Data: "10:30",
      },
      {
        Label: "Departure Date Time",
        Data: "10:30",
      },
      {
        Label: "Adult Cost",
        Data: "INR 1000",
      },
      {
        Label: "Child Cost",
        Data: "INR 1500",
      },
    ],
  },
];

const quotationData = {
  QuotationNumber: "",
  Header: {
    QuotationStage: "",
    QuotationStatus: "",
    QuotationVersion: "",
    QuotationChangeLog: [
      {
        ChangeDateTime: "",
        ChangedByID: "",
        ChangeByValue: "",
        ChangeSetDetail: [
          {
            ChangeFrom: "",
            ChangeTo: "",
          },
        ],
      },
    ],
  },
  QuatationSummary: {
    QuatationSubject: "",
    QuatationHotelCategory: "",
    QutationPaxSlabType: "",
    QutationHotelMarkupType: "",
    QutationHotelStartCategory: "",
    QutationInbuiltPackages: "",
  },
  TourSummary: {
    TourId: "", //auto generate
    FromDate: "",
    Todate: "",
    NumberOfDays: "",
    NumberOfNights: "",
    PaxCount: "",
    Destiniation: "1~Delhi^2~Jaipur^3~Agra",
    TourType: "",
    TourServiceSummary: "1~Transfer~Hotel^2~Hotel~sightseen~Lunch^3~transfer",
  },
  Pax: {
    AdultCount: "",
    ChildCount: "",
    InfantCount: "",
    ChildAge: [
      {
        ChildNumber: "",
        ChildAge: "",
      },
    ],
  },
  CustomerCost: {
    CustomerCostDetails: {
      QuotationCost: "",
      Paidvalue: "",
    },
    CustomerPaymentDetails: [
      {
        PaymentMethod: "",
        PaymentValue: "",
        PaymnetCurrency: "",
      },
    ],
  },

  OptinalExperience: {
    ServiceDetails: [
      {
        ServiceType: "",
        ServiceName: "",
        ServiceAdultCost: "",
        ServiceChildCost: "",
        ServiceGroupCost: "",
        ServiceDay: "",
      },
    ],
  },
  Days: [
    {
      Day: "1",
      DayUniqueId: "day_66f0fbeee646b9.04425310",
      DestiniationID: "",
      DestiniationName: "Rajsthan",
      DayTotal: "23 Sep | Mon",
      DayTaxValue: "",
      DayCurrencyType: "",
      DayServices: [
        {
          ServiceType: "Hotel", // Guide/Hotel/Transport/Train/
          ServiceId: "",
          ServicePrice: "",
          ServiceTaxType: "",
          ServiceTaxRate: "",
          ServiceTaxValue: "",
          ServiceSourceCurrency: "",
          ServiceCurrencyConversionRate: "",
          ServiceTargetCurrency: "",
          ServiceDetails: [
            {
              ItemName: "Birla Temple",
              ItemCategory: "10:30",
              ItemType: "1200",
              ItemGrade: "1000",
              ItemClass: "",
              ItemFromDate: "",
              ItemFromTime: "",
              ItemToDate: "",
              ItemToTime: "",
              ItemUnitCost: "",
              ItemDiscount: "",
              ItemCurrency: "",
              ItemQty: "",
              ItemTotalPrice: "",
              ItemTaxValue: "",
              ItemTaxRate: "",
              ItemGrossTotalValue: "",
              ItemSupplierDeatil: {
                ItemSupplierId: "",
                ItemSupplierName: "",
                ItemSupplierRate: "",
                ItemSupplierCurrency: "",
                SupplierVoucherNumber: "",
                SupplierVoucherDate: "",
                SupplierVoucherValue: "",
                SupplierPaymentStatus: "",
              },
            },
          ],
        },
        {
          ServiceType: "Arrival", // Guide/Hotel/Transport/Train/
          ServiceId: "",
          ServicePrice: "",
          ServiceTaxType: "",
          ServiceTaxRate: "",
          ServiceTaxValue: "",
          ServiceSourceCurrency: "",
          ServiceCurrencyConversionRate: "",
          ServiceTargetCurrency: "",
          ServiceDetails: [
            {
              ItemName: "Air-India 13989",
              ItemCategory: "First Class",
              ItemType: "Delhi-Mumbai",
              ItemGrade: "10-10-2024",
              ItemClass: "10:15",
              ItemFromDate: "INR 1500",
              ItemFromTime: "INR 1200",
              ItemToDate: "INR 1000",
              ItemToTime: "",
              ItemUnitCost: "",
              ItemDiscount: "",
              ItemCurrency: "",
              ItemQty: "",
              ItemTotalPrice: "",
              ItemTaxValue: "",
              ItemTaxRate: "",
              ItemGrossTotalValue: "",
              ItemSupplierDeatil: {
                ItemSupplierId: "",
                ItemSupplierName: "",
                ItemSupplierRate: "",
                ItemSupplierCurrency: "",
                SupplierVoucherNumber: "",
                SupplierVoucherDate: "",
                SupplierVoucherValue: "",
                SupplierPaymentStatus: "",
              },
            },
          ],
        },
        {
          ServiceType: "Departure", // Guide/Hotel/Transport/Train/
          ServiceId: "",
          ServicePrice: "",
          ServiceTaxType: "",
          ServiceTaxRate: "",
          ServiceTaxValue: "",
          ServiceSourceCurrency: "",
          ServiceCurrencyConversionRate: "",
          ServiceTargetCurrency: "",
          ServiceDetails: [
            {
              ItemName: "Air-India 13989",
              ItemCategory: "First Class",
              ItemType: "Delhi-Mumbai",
              ItemGrade: "10-10-2024",
              ItemClass: "10:15",
              ItemFromDate: "INR 1500",
              ItemFromTime: "INR 1200",
              ItemToDate: "INR 1000",
              ItemToTime: "",
              ItemUnitCost: "",
              ItemDiscount: "",
              ItemCurrency: "",
              ItemQty: "",
              ItemTotalPrice: "",
              ItemTaxValue: "",
              ItemTaxRate: "",
              ItemGrossTotalValue: "",
              ItemSupplierDeatil: {
                ItemSupplierId: "",
                ItemSupplierName: "",
                ItemSupplierRate: "",
                ItemSupplierCurrency: "",
                SupplierVoucherNumber: "",
                SupplierVoucherDate: "",
                SupplierVoucherValue: "",
                SupplierPaymentStatus: "",
              },
            },
          ],
        },
        {
          ServiceType: "Monument", // Guide/Hotel/Transport/Train/
          ServiceId: "",
          ServicePrice: "",
          ServiceTaxType: "",
          ServiceTaxRate: "",
          ServiceTaxValue: "",
          ServiceSourceCurrency: "",
          ServiceCurrencyConversionRate: "",
          ServiceTargetCurrency: "",
          ServiceDetails: [
            {
              ItemName: "Birla Temple",
              ItemCategory: "10:45",
              ItemType: "INR 1500",
              ItemGrade: "INR 1200",
              ItemClass: "INR 1000",
              ItemFromDate: "",
              ItemFromTime: "",
              ItemToDate: "",
              ItemToTime: "",
              ItemUnitCost: "",
              ItemDiscount: "",
              ItemCurrency: "",
              ItemQty: "",
              ItemTotalPrice: "",
              ItemTaxValue: "",
              ItemTaxRate: "",
              ItemGrossTotalValue: "",
              ItemSupplierDeatil: {
                ItemSupplierId: "",
                ItemSupplierName: "",
                ItemSupplierRate: "",
                ItemSupplierCurrency: "",
                SupplierVoucherNumber: "",
                SupplierVoucherDate: "",
                SupplierVoucherValue: "",
                SupplierPaymentStatus: "",
              },
            },
          ],
        },
        {
          ServiceType: "Activity", // Guide/Hotel/Transport/Train/
          ServiceId: "",
          ServicePrice: "",
          ServiceTaxType: "",
          ServiceTaxRate: "",
          ServiceTaxValue: "",
          ServiceSourceCurrency: "",
          ServiceCurrencyConversionRate: "",
          ServiceTargetCurrency: "",
          ServiceDetails: [
            {
              ItemName: "Deep Diving",
              ItemCategory: "10:45",
              ItemType: "11:45",
              ItemGrade: "INR 1200",
              ItemClass: "INR 1000",
              ItemFromDate: "10 PAX",
              ItemFromTime: "INR 1500",
              ItemToDate: "",
              ItemToTime: "",
              ItemUnitCost: "",
              ItemDiscount: "",
              ItemCurrency: "",
              ItemQty: "",
              ItemTotalPrice: "",
              ItemTaxValue: "",
              ItemTaxRate: "",
              ItemGrossTotalValue: "",
              ItemSupplierDeatil: {
                ItemSupplierId: "",
                ItemSupplierName: "",
                ItemSupplierRate: "",
                ItemSupplierCurrency: "",
                SupplierVoucherNumber: "",
                SupplierVoucherDate: "",
                SupplierVoucherValue: "",
                SupplierPaymentStatus: "",
              },
            },
          ],
        },
      ],
    },
    {
      Day: "2",
      DayUniqueId: "day_66f0fbeee646b9.04425310",
      DestiniationID: "",
      DestiniationName: "Mumbai",
      DayTotal: "24 Sep | Tue",
      DayTaxValue: "",
      DayCurrencyType: "",
      DayServices: [
        {
          ServiceType: "Hotel", // Guide/Hotel/Transport/Train/
          ServiceId: "",
          ServicePrice: "",
          ServiceTaxType: "",
          ServiceTaxRate: "",
          ServiceTaxValue: "",
          ServiceSourceCurrency: "",
          ServiceCurrencyConversionRate: "",
          ServiceTargetCurrency: "",
          ServiceDetails: [
            {
              ItemName: "Taj Hotel",
              ItemCategory: "10:30",
              ItemType: "1200",
              ItemGrade: "1000",
              ItemClass: "",
              ItemFromDate: "",
              ItemFromTime: "",
              ItemToDate: "",
              ItemToTime: "",
              ItemUnitCost: "",
              ItemDiscount: "",
              ItemCurrency: "",
              ItemQty: "",
              ItemTotalPrice: "",
              ItemTaxValue: "",
              ItemTaxRate: "",
              ItemGrossTotalValue: "",
              ItemSupplierDeatil: {
                ItemSupplierId: "",
                ItemSupplierName: "",
                ItemSupplierRate: "",
                ItemSupplierCurrency: "",
                SupplierVoucherNumber: "",
                SupplierVoucherDate: "",
                SupplierVoucherValue: "",
                SupplierPaymentStatus: "",
              },
            },
          ],
        },
        {
          ServiceType: "Arrival", // Guide/Hotel/Transport/Train/
          ServiceId: "",
          ServicePrice: "",
          ServiceTaxType: "",
          ServiceTaxRate: "",
          ServiceTaxValue: "",
          ServiceSourceCurrency: "",
          ServiceCurrencyConversionRate: "",
          ServiceTargetCurrency: "",
          ServiceDetails: [
            {
              ItemName: "Vistara 13989",
              ItemCategory: "First Class",
              ItemType: "Delhi-Mumbai",
              ItemGrade: "10-10-2024",
              ItemClass: "10:15",
              ItemFromDate: "INR 1500",
              ItemFromTime: "INR 1200",
              ItemToDate: "INR 1000",
              ItemToTime: "",
              ItemUnitCost: "",
              ItemDiscount: "",
              ItemCurrency: "",
              ItemQty: "",
              ItemTotalPrice: "",
              ItemTaxValue: "",
              ItemTaxRate: "",
              ItemGrossTotalValue: "",
              ItemSupplierDeatil: {
                ItemSupplierId: "",
                ItemSupplierName: "",
                ItemSupplierRate: "",
                ItemSupplierCurrency: "",
                SupplierVoucherNumber: "",
                SupplierVoucherDate: "",
                SupplierVoucherValue: "",
                SupplierPaymentStatus: "",
              },
            },
          ],
        },
        {
          ServiceType: "Departure", // Guide/Hotel/Transport/Train/
          ServiceId: "",
          ServicePrice: "",
          ServiceTaxType: "",
          ServiceTaxRate: "",
          ServiceTaxValue: "",
          ServiceSourceCurrency: "",
          ServiceCurrencyConversionRate: "",
          ServiceTargetCurrency: "",
          ServiceDetails: [
            {
              ItemName: "Vistara 13989",
              ItemCategory: "First Class",
              ItemType: "Delhi-Mumbai",
              ItemGrade: "10-10-2024",
              ItemClass: "10:15",
              ItemFromDate: "INR 1500",
              ItemFromTime: "INR 1200",
              ItemToDate: "INR 1000",
              ItemToTime: "",
              ItemUnitCost: "",
              ItemDiscount: "",
              ItemCurrency: "",
              ItemQty: "",
              ItemTotalPrice: "",
              ItemTaxValue: "",
              ItemTaxRate: "",
              ItemGrossTotalValue: "",
              ItemSupplierDeatil: {
                ItemSupplierId: "",
                ItemSupplierName: "",
                ItemSupplierRate: "",
                ItemSupplierCurrency: "",
                SupplierVoucherNumber: "",
                SupplierVoucherDate: "",
                SupplierVoucherValue: "",
                SupplierPaymentStatus: "",
              },
            },
          ],
        },
        {
          ServiceType: "Monument", // Guide/Hotel/Transport/Train/
          ServiceId: "",
          ServicePrice: "",
          ServiceTaxType: "",
          ServiceTaxRate: "",
          ServiceTaxValue: "",
          ServiceSourceCurrency: "",
          ServiceCurrencyConversionRate: "",
          ServiceTargetCurrency: "",
          ServiceDetails: [
            {
              ItemName: "Gateway of India",
              ItemCategory: "10:45",
              ItemType: "INR 1500",
              ItemGrade: "INR 1200",
              ItemClass: "INR 1000",
              ItemFromDate: "",
              ItemFromTime: "",
              ItemToDate: "",
              ItemToTime: "",
              ItemUnitCost: "",
              ItemDiscount: "",
              ItemCurrency: "",
              ItemQty: "",
              ItemTotalPrice: "",
              ItemTaxValue: "",
              ItemTaxRate: "",
              ItemGrossTotalValue: "",
              ItemSupplierDeatil: {
                ItemSupplierId: "",
                ItemSupplierName: "",
                ItemSupplierRate: "",
                ItemSupplierCurrency: "",
                SupplierVoucherNumber: "",
                SupplierVoucherDate: "",
                SupplierVoucherValue: "",
                SupplierPaymentStatus: "",
              },
            },
          ],
        },
        {
          ServiceType: "Activity", // Guide/Hotel/Transport/Train/
          ServiceId: "",
          ServicePrice: "",
          ServiceTaxType: "",
          ServiceTaxRate: "",
          ServiceTaxValue: "",
          ServiceSourceCurrency: "",
          ServiceCurrencyConversionRate: "",
          ServiceTargetCurrency: "",
          ServiceDetails: [
            {
              ItemName: "Boating",
              ItemCategory: "10:45",
              ItemType: "11:45",
              ItemGrade: "INR 1200",
              ItemClass: "INR 1000",
              ItemFromDate: "10 PAX",
              ItemFromTime: "INR 1500",
              ItemToDate: "",
              ItemToTime: "",
              ItemUnitCost: "",
              ItemDiscount: "",
              ItemCurrency: "",
              ItemQty: "",
              ItemTotalPrice: "",
              ItemTaxValue: "",
              ItemTaxRate: "",
              ItemGrossTotalValue: "",
              ItemSupplierDeatil: {
                ItemSupplierId: "",
                ItemSupplierName: "",
                ItemSupplierRate: "",
                ItemSupplierCurrency: "",
                SupplierVoucherNumber: "",
                SupplierVoucherDate: "",
                SupplierVoucherValue: "",
                SupplierPaymentStatus: "",
              },
            },
          ],
        },
      ],
    },
    {
      Day: "3",
      DayUniqueId: "day_66f0fbeee646b9.04425310",
      DestiniationID: "",
      DestiniationName: "Gujarat Surat",
      DayTotal: "25 Sep | Wed",
      DayTaxValue: "",
      DayCurrencyType: "",
      DayServices: [
        {
          ServiceType: "Hotel", // Guide/Hotel/Transport/Train/
          ServiceId: "",
          ServicePrice: "",
          ServiceTaxType: "",
          ServiceTaxRate: "",
          ServiceTaxValue: "",
          ServiceSourceCurrency: "",
          ServiceCurrencyConversionRate: "",
          ServiceTargetCurrency: "",
          ServiceDetails: [
            {
              ItemName: "Ginger Surat",
              ItemCategory: "10:30",
              ItemType: "1200",
              ItemGrade: "1000",
              ItemClass: "",
              ItemFromDate: "",
              ItemFromTime: "",
              ItemToDate: "",
              ItemToTime: "",
              ItemUnitCost: "",
              ItemDiscount: "",
              ItemCurrency: "",
              ItemQty: "",
              ItemTotalPrice: "",
              ItemTaxValue: "",
              ItemTaxRate: "",
              ItemGrossTotalValue: "",
              ItemSupplierDeatil: {
                ItemSupplierId: "",
                ItemSupplierName: "",
                ItemSupplierRate: "",
                ItemSupplierCurrency: "",
                SupplierVoucherNumber: "",
                SupplierVoucherDate: "",
                SupplierVoucherValue: "",
                SupplierPaymentStatus: "",
              },
            },
          ],
        },
        {
          ServiceType: "Arrival", // Guide/Hotel/Transport/Train/
          ServiceId: "",
          ServicePrice: "",
          ServiceTaxType: "",
          ServiceTaxRate: "",
          ServiceTaxValue: "",
          ServiceSourceCurrency: "",
          ServiceCurrencyConversionRate: "",
          ServiceTargetCurrency: "",
          ServiceDetails: [
            {
              ItemName: "Vistara 13989",
              ItemCategory: "First Class",
              ItemType: "Delhi-Mumbai",
              ItemGrade: "10-10-2024",
              ItemClass: "10:15",
              ItemFromDate: "INR 1500",
              ItemFromTime: "INR 1200",
              ItemToDate: "INR 1000",
              ItemToTime: "",
              ItemUnitCost: "",
              ItemDiscount: "",
              ItemCurrency: "",
              ItemQty: "",
              ItemTotalPrice: "",
              ItemTaxValue: "",
              ItemTaxRate: "",
              ItemGrossTotalValue: "",
              ItemSupplierDeatil: {
                ItemSupplierId: "",
                ItemSupplierName: "",
                ItemSupplierRate: "",
                ItemSupplierCurrency: "",
                SupplierVoucherNumber: "",
                SupplierVoucherDate: "",
                SupplierVoucherValue: "",
                SupplierPaymentStatus: "",
              },
            },
          ],
        },
        {
          ServiceType: "Departure", // Guide/Hotel/Transport/Train/
          ServiceId: "",
          ServicePrice: "",
          ServiceTaxType: "",
          ServiceTaxRate: "",
          ServiceTaxValue: "",
          ServiceSourceCurrency: "",
          ServiceCurrencyConversionRate: "",
          ServiceTargetCurrency: "",
          ServiceDetails: [
            {
              ItemName: "Vistara 13989",
              ItemCategory: "First Class",
              ItemType: "Delhi-Mumbai",
              ItemGrade: "10-10-2024",
              ItemClass: "10:15",
              ItemFromDate: "INR 1500",
              ItemFromTime: "INR 1200",
              ItemToDate: "INR 1000",
              ItemToTime: "",
              ItemUnitCost: "",
              ItemDiscount: "",
              ItemCurrency: "",
              ItemQty: "",
              ItemTotalPrice: "",
              ItemTaxValue: "",
              ItemTaxRate: "",
              ItemGrossTotalValue: "",
              ItemSupplierDeatil: {
                ItemSupplierId: "",
                ItemSupplierName: "",
                ItemSupplierRate: "",
                ItemSupplierCurrency: "",
                SupplierVoucherNumber: "",
                SupplierVoucherDate: "",
                SupplierVoucherValue: "",
                SupplierPaymentStatus: "",
              },
            },
          ],
        },
        {
          ServiceType: "Monument", // Guide/Hotel/Transport/Train/
          ServiceId: "",
          ServicePrice: "",
          ServiceTaxType: "",
          ServiceTaxRate: "",
          ServiceTaxValue: "",
          ServiceSourceCurrency: "",
          ServiceCurrencyConversionRate: "",
          ServiceTargetCurrency: "",
          ServiceDetails: [
            {
              ItemName: "Ginger Surat",
              ItemCategory: "10:45",
              ItemType: "INR 1500",
              ItemGrade: "INR 1200",
              ItemClass: "INR 1000",
              ItemFromDate: "",
              ItemFromTime: "",
              ItemToDate: "",
              ItemToTime: "",
              ItemUnitCost: "",
              ItemDiscount: "",
              ItemCurrency: "",
              ItemQty: "",
              ItemTotalPrice: "",
              ItemTaxValue: "",
              ItemTaxRate: "",
              ItemGrossTotalValue: "",
              ItemSupplierDeatil: {
                ItemSupplierId: "",
                ItemSupplierName: "",
                ItemSupplierRate: "",
                ItemSupplierCurrency: "",
                SupplierVoucherNumber: "",
                SupplierVoucherDate: "",
                SupplierVoucherValue: "",
                SupplierPaymentStatus: "",
              },
            },
          ],
        },
        {
          ServiceType: "Activity", // Guide/Hotel/Transport/Train/
          ServiceId: "",
          ServicePrice: "",
          ServiceTaxType: "",
          ServiceTaxRate: "",
          ServiceTaxValue: "",
          ServiceSourceCurrency: "",
          ServiceCurrencyConversionRate: "",
          ServiceTargetCurrency: "",
          ServiceDetails: [
            {
              ItemName: "Visting",
              ItemCategory: "10:45",
              ItemType: "11:45",
              ItemGrade: "INR 1200",
              ItemClass: "INR 1000",
              ItemFromDate: "10 PAX",
              ItemFromTime: "INR 1500",
              ItemToDate: "",
              ItemToTime: "",
              ItemUnitCost: "",
              ItemDiscount: "",
              ItemCurrency: "",
              ItemQty: "",
              ItemTotalPrice: "",
              ItemTaxValue: "",
              ItemTaxRate: "",
              ItemGrossTotalValue: "",
              ItemSupplierDeatil: {
                ItemSupplierId: "",
                ItemSupplierName: "",
                ItemSupplierRate: "",
                ItemSupplierCurrency: "",
                SupplierVoucherNumber: "",
                SupplierVoucherDate: "",
                SupplierVoucherValue: "",
                SupplierPaymentStatus: "",
              },
            },
          ],
        },
      ],
    },
  ],
};

const quotationLabel = [
  {
    ServiceType: "Arrival",
    Label: [
      "Flight Name/Number",
      "Flight Class Name",
      "Arrival Departure",
      "Arrival Date Time",
      "Departure Date Time",
      "Adult Cost",
      "Child Cost",
    ],
  },
  {
    ServiceType: "Departure",
    Label: [
      "Flight Name/Number",
      "Flight Class Name",
      "Arrival Departure",
      "Arrival Date Time",
      "Departure Date Time",
      "Adult Cost",
      "Child Cost",
    ],
  },
  {
    ServiceType: "Monument",
    Label: ["Monument Name", "Adult Cost", "Child Cost", "Start End/Time"],
  },
  {
    ServiceType: "Hotel",
    Label: ["Hotel Name", "Service Cost", "Meal Plan", "Tariff Type"],
  },
  {
    ServiceType: "Activity",
    Label: [
      "Activity Name",
      "Pax Slab",
      "Per Pax Cost",
      "Arrival Date Time",
      "Departure Date Time",
      "Adult Cost",
      "Child Cost",
    ],
  },
];



export default data;
export { quotationData, quotationLabel };
