import ArrivalImage from "/global_assets/images/qoutation/Arrival.png";
import Departure from "/global_assets/images/qoutation/Departure1.png";
import Monument from "/global_assets/images/qoutation/monument.png";
import Hotel from "/global_assets/images/qoutation/hotel.png";
import Activity from "/global_assets/images/qoutation/activity.png";

const data = [
  {
    Name: {
      Name: "Arrival",
      Logo: ArrivalImage,
    },
    Columns: [
      {
        Label: "Flight Name/Number",
        Data: "Air-India-13989",
      },
      {
        Label: "Flight Class Name",
        Data: "First Class",
      },
      {
        Label: "Arrival Departure",
        Data: "New Delhi-Mumbai",
      },
      {
        Label: "Arrival Date Time",
        Data: "10:30",
      },
      {
        Label: "Departure Date Time",
        Data: "11:35",
      },
      {
        Label: "Adult Cost",
        Data: "INR 1500",
      },
      {
        Label: "Child Cost",
        Data: "INR 1200",
      },
    ],
  },
  {
    Name: {
      Name: "Departure",
      Logo: Departure,
    },
    Columns: [
      {
        Label: "Flight Name/Number",
        Data: "Air-India-13989",
      },
      {
        Label: "Flight Class Name",
        Data: "First Class",
      },
      {
        Label: "Arrival Departure",
        Data: "New Delhi-Mumbai",
      },
      {
        Label: "Arrival Date Time",
        Data: "10:30",
      },
      {
        Label: "Departure Date Time",
        Data: "11:35",
      },
      {
        Label: "Adult Cost",
        Data: "INR 1500",
      },
      {
        Label: "Child Cost",
        Data: "INR 1200",
      },
    ],
  },
  {
    Name: {
      Name: "Monument",
      Logo: Monument,
    },
    Columns: [
      {
        Label: "Monument Name",
        Data: "Birla Temple",
      },
      {
        Label: "Adult Cost",
        Data: "1200",
      },
      {
        Label: "Child Cost",
        Data: "1000",
      },
      {
        Label: "Start/End Time",
        Data: "10:30",
      },
    ],
  },
  {
    Name: {
      Name: "Hotel",
      Logo: Hotel,
    },
    Columns: [
      {
        Label: "Hotel Name",
        Data: "Birla Temple",
      },
      {
        Label: "Service Cost",
        Data: "1200",
      },
      {
        Label: "Meal Plan",
        Data: "1000",
      },
      {
        Label: "Tariff Type",
        Data: "10:30",
      },
    ],
  },
  {
    Name: {
      Name: "Activity",
      Logo: Activity,
    },
    Columns: [
      {
        Label: "Activity Name",
        Data: "Deep Diving",
      },
      {
        Label: "Pax Slab",
        Data: "10pax",
      },
      {
        Label: "Per Pax Cost",
        Data: "INR 1200",
      },
      {
        Label: "Arrival Date Time",
        Data: "10:30",
      },
      {
        Label: "Departure Date Time",
        Data: "10:30",
      },
      {
        Label: "Adult Cost",
        Data: "INR 1000",
      },
      {
        Label: "Child Cost",
        Data: "INR 1500",
      },
    ],
  },
];

const quotationData = {
  QuotationNumber: "",
  Header: {
    QuotationStage: "",
    QuotationStatus: "",
    QuotationVersion: "",
    QuotationChangeLog: [
      {
        ChangeDateTime: "",
        ChangedByID: "",
        ChangeByValue: "",
        ChangeSetDetail: [
          {
            ChangeFrom: "",
            ChangeTo: "",
          },
        ],
      },
    ],
  },
  QuatationSummary: {
    QuatationSubject: "",
    QuatationHotelCategory: "",
    QutationPaxSlabType: "",
    QutationHotelMarkupType: "",
    QutationHotelStartCategory: "",
    QutationInbuiltPackages: "",
  },
  TourSummary: {
    TourId: "", //auto generate
    FromDate: "",
    Todate: "",
    NumberOfDays: "",
    NumberOfNights: "",
    PaxCount: "",
    Destiniation: "1~Delhi^2~Jaipur^3~Agra",
    TourType: "",
    TourServiceSummary: "1~Transfer~Hotel^2~Hotel~sightseen~Lunch^3~transfer",
  },
  Pax: {
    AdultCount: "",
    ChildCount: "",
    InfantCount: "",
    ChildAge: [
      {
        ChildNumber: "",
        ChildAge: "",
      },
    ],
  },
  CustomerCost: {
    CustomerCostDetails: {
      QuotationCost: "",
      Paidvalue: "",
    },
    CustomerPaymentDetails: [
      {
        PaymentMethod: "",
        PaymentValue: "",
        PaymnetCurrency: "",
      },
    ],
  },

  OptinalExperience: {
    ServiceDetails: [
      {
        ServiceType: "",
        ServiceName: "",
        ServiceAdultCost: "",
        ServiceChildCost: "",
        ServiceGroupCost: "",
        ServiceDay: "",
      },
    ],
  },
  Days: [
    {
      Day: "1",
      DayUniqueId: "day_66f0fbeee646b9.04425310",
      DestiniationID: "",
      DestiniationName: "Rajsthan",
      DayTotal: "23 Sep | Mon",
      DayTaxValue: "",
      DayCurrencyType: "",
      DayServices: [
        {
          ServiceType: "Hotel", // Guide/Hotel/Transport/Train/
          ServiceId: "",
          ServicePrice: "",
          ServiceTaxType: "",
          ServiceTaxRate: "",
          ServiceTaxValue: "",
          ServiceSourceCurrency: "",
          ServiceCurrencyConversionRate: "",
          ServiceTargetCurrency: "",
          ServiceDetails: [
            {
              ItemName: "Birla Temple",
              ItemCategory: "10:30",
              ItemType: "1200",
              ItemGrade: "1000",
              ItemClass: "",
              ItemFromDate: "",
              ItemFromTime: "",
              ItemToDate: "",
              ItemToTime: "",
              ItemUnitCost: "",
              ItemDiscount: "",
              ItemCurrency: "",
              ItemQty: "",
              ItemTotalPrice: "",
              ItemTaxValue: "",
              ItemTaxRate: "",
              ItemGrossTotalValue: "",
              ItemSupplierDeatil: {
                ItemSupplierId: "",
                ItemSupplierName: "",
                ItemSupplierRate: "",
                ItemSupplierCurrency: "",
                SupplierVoucherNumber: "",
                SupplierVoucherDate: "",
                SupplierVoucherValue: "",
                SupplierPaymentStatus: "",
              },
            },
          ],
        },
        {
          ServiceType: "Arrival", // Guide/Hotel/Transport/Train/
          ServiceId: "",
          ServicePrice: "",
          ServiceTaxType: "",
          ServiceTaxRate: "",
          ServiceTaxValue: "",
          ServiceSourceCurrency: "",
          ServiceCurrencyConversionRate: "",
          ServiceTargetCurrency: "",
          ServiceDetails: [
            {
              ItemName: "Air-India 13989",
              ItemCategory: "First Class",
              ItemType: "Delhi-Mumbai",
              ItemGrade: "10-10-2024",
              ItemClass: "10:15",
              ItemFromDate: "INR 1500",
              ItemFromTime: "INR 1200",
              ItemToDate: "INR 1000",
              ItemToTime: "",
              ItemUnitCost: "",
              ItemDiscount: "",
              ItemCurrency: "",
              ItemQty: "",
              ItemTotalPrice: "",
              ItemTaxValue: "",
              ItemTaxRate: "",
              ItemGrossTotalValue: "",
              ItemSupplierDeatil: {
                ItemSupplierId: "",
                ItemSupplierName: "",
                ItemSupplierRate: "",
                ItemSupplierCurrency: "",
                SupplierVoucherNumber: "",
                SupplierVoucherDate: "",
                SupplierVoucherValue: "",
                SupplierPaymentStatus: "",
              },
            },
          ],
        },
        {
          ServiceType: "Departure", // Guide/Hotel/Transport/Train/
          ServiceId: "",
          ServicePrice: "",
          ServiceTaxType: "",
          ServiceTaxRate: "",
          ServiceTaxValue: "",
          ServiceSourceCurrency: "",
          ServiceCurrencyConversionRate: "",
          ServiceTargetCurrency: "",
          ServiceDetails: [
            {
              ItemName: "Air-India 13989",
              ItemCategory: "First Class",
              ItemType: "Delhi-Mumbai",
              ItemGrade: "10-10-2024",
              ItemClass: "10:15",
              ItemFromDate: "INR 1500",
              ItemFromTime: "INR 1200",
              ItemToDate: "INR 1000",
              ItemToTime: "",
              ItemUnitCost: "",
              ItemDiscount: "",
              ItemCurrency: "",
              ItemQty: "",
              ItemTotalPrice: "",
              ItemTaxValue: "",
              ItemTaxRate: "",
              ItemGrossTotalValue: "",
              ItemSupplierDeatil: {
                ItemSupplierId: "",
                ItemSupplierName: "",
                ItemSupplierRate: "",
                ItemSupplierCurrency: "",
                SupplierVoucherNumber: "",
                SupplierVoucherDate: "",
                SupplierVoucherValue: "",
                SupplierPaymentStatus: "",
              },
            },
          ],
        },
        {
          ServiceType: "Monument", // Guide/Hotel/Transport/Train/
          ServiceId: "",
          ServicePrice: "",
          ServiceTaxType: "",
          ServiceTaxRate: "",
          ServiceTaxValue: "",
          ServiceSourceCurrency: "",
          ServiceCurrencyConversionRate: "",
          ServiceTargetCurrency: "",
          ServiceDetails: [
            {
              ItemName: "Birla Temple",
              ItemCategory: "10:45",
              ItemType: "INR 1500",
              ItemGrade: "INR 1200",
              ItemClass: "INR 1000",
              ItemFromDate: "",
              ItemFromTime: "",
              ItemToDate: "",
              ItemToTime: "",
              ItemUnitCost: "",
              ItemDiscount: "",
              ItemCurrency: "",
              ItemQty: "",
              ItemTotalPrice: "",
              ItemTaxValue: "",
              ItemTaxRate: "",
              ItemGrossTotalValue: "",
              ItemSupplierDeatil: {
                ItemSupplierId: "",
                ItemSupplierName: "",
                ItemSupplierRate: "",
                ItemSupplierCurrency: "",
                SupplierVoucherNumber: "",
                SupplierVoucherDate: "",
                SupplierVoucherValue: "",
                SupplierPaymentStatus: "",
              },
            },
          ],
        },
        {
          ServiceType: "Activity", // Guide/Hotel/Transport/Train/
          ServiceId: "",
          ServicePrice: "",
          ServiceTaxType: "",
          ServiceTaxRate: "",
          ServiceTaxValue: "",
          ServiceSourceCurrency: "",
          ServiceCurrencyConversionRate: "",
          ServiceTargetCurrency: "",
          ServiceDetails: [
            {
              ItemName: "Deep Diving",
              ItemCategory: "10:45",
              ItemType: "11:45",
              ItemGrade: "INR 1200",
              ItemClass: "INR 1000",
              ItemFromDate: "10 PAX",
              ItemFromTime: "INR 1500",
              ItemToDate: "",
              ItemToTime: "",
              ItemUnitCost: "",
              ItemDiscount: "",
              ItemCurrency: "",
              ItemQty: "",
              ItemTotalPrice: "",
              ItemTaxValue: "",
              ItemTaxRate: "",
              ItemGrossTotalValue: "",
              ItemSupplierDeatil: {
                ItemSupplierId: "",
                ItemSupplierName: "",
                ItemSupplierRate: "",
                ItemSupplierCurrency: "",
                SupplierVoucherNumber: "",
                SupplierVoucherDate: "",
                SupplierVoucherValue: "",
                SupplierPaymentStatus: "",
              },
            },
          ],
        },
      ],
    },
    {
      Day: "2",
      DayUniqueId: "day_66f0fbeee646b9.04425310",
      DestiniationID: "",
      DestiniationName: "Mumbai",
      DayTotal: "24 Sep | Tue",
      DayTaxValue: "",
      DayCurrencyType: "",
      DayServices: [
        {
          ServiceType: "Hotel", // Guide/Hotel/Transport/Train/
          ServiceId: "",
          ServicePrice: "",
          ServiceTaxType: "",
          ServiceTaxRate: "",
          ServiceTaxValue: "",
          ServiceSourceCurrency: "",
          ServiceCurrencyConversionRate: "",
          ServiceTargetCurrency: "",
          ServiceDetails: [
            {
              ItemName: "Taj Hotel",
              ItemCategory: "10:30",
              ItemType: "1200",
              ItemGrade: "1000",
              ItemClass: "",
              ItemFromDate: "",
              ItemFromTime: "",
              ItemToDate: "",
              ItemToTime: "",
              ItemUnitCost: "",
              ItemDiscount: "",
              ItemCurrency: "",
              ItemQty: "",
              ItemTotalPrice: "",
              ItemTaxValue: "",
              ItemTaxRate: "",
              ItemGrossTotalValue: "",
              ItemSupplierDeatil: {
                ItemSupplierId: "",
                ItemSupplierName: "",
                ItemSupplierRate: "",
                ItemSupplierCurrency: "",
                SupplierVoucherNumber: "",
                SupplierVoucherDate: "",
                SupplierVoucherValue: "",
                SupplierPaymentStatus: "",
              },
            },
          ],
        },
        {
          ServiceType: "Arrival", // Guide/Hotel/Transport/Train/
          ServiceId: "",
          ServicePrice: "",
          ServiceTaxType: "",
          ServiceTaxRate: "",
          ServiceTaxValue: "",
          ServiceSourceCurrency: "",
          ServiceCurrencyConversionRate: "",
          ServiceTargetCurrency: "",
          ServiceDetails: [
            {
              ItemName: "Vistara 13989",
              ItemCategory: "First Class",
              ItemType: "Delhi-Mumbai",
              ItemGrade: "10-10-2024",
              ItemClass: "10:15",
              ItemFromDate: "INR 1500",
              ItemFromTime: "INR 1200",
              ItemToDate: "INR 1000",
              ItemToTime: "",
              ItemUnitCost: "",
              ItemDiscount: "",
              ItemCurrency: "",
              ItemQty: "",
              ItemTotalPrice: "",
              ItemTaxValue: "",
              ItemTaxRate: "",
              ItemGrossTotalValue: "",
              ItemSupplierDeatil: {
                ItemSupplierId: "",
                ItemSupplierName: "",
                ItemSupplierRate: "",
                ItemSupplierCurrency: "",
                SupplierVoucherNumber: "",
                SupplierVoucherDate: "",
                SupplierVoucherValue: "",
                SupplierPaymentStatus: "",
              },
            },
          ],
        },
        {
          ServiceType: "Departure", // Guide/Hotel/Transport/Train/
          ServiceId: "",
          ServicePrice: "",
          ServiceTaxType: "",
          ServiceTaxRate: "",
          ServiceTaxValue: "",
          ServiceSourceCurrency: "",
          ServiceCurrencyConversionRate: "",
          ServiceTargetCurrency: "",
          ServiceDetails: [
            {
              ItemName: "Vistara 13989",
              ItemCategory: "First Class",
              ItemType: "Delhi-Mumbai",
              ItemGrade: "10-10-2024",
              ItemClass: "10:15",
              ItemFromDate: "INR 1500",
              ItemFromTime: "INR 1200",
              ItemToDate: "INR 1000",
              ItemToTime: "",
              ItemUnitCost: "",
              ItemDiscount: "",
              ItemCurrency: "",
              ItemQty: "",
              ItemTotalPrice: "",
              ItemTaxValue: "",
              ItemTaxRate: "",
              ItemGrossTotalValue: "",
              ItemSupplierDeatil: {
                ItemSupplierId: "",
                ItemSupplierName: "",
                ItemSupplierRate: "",
                ItemSupplierCurrency: "",
                SupplierVoucherNumber: "",
                SupplierVoucherDate: "",
                SupplierVoucherValue: "",
                SupplierPaymentStatus: "",
              },
            },
          ],
        },
        {
          ServiceType: "Monument", // Guide/Hotel/Transport/Train/
          ServiceId: "",
          ServicePrice: "",
          ServiceTaxType: "",
          ServiceTaxRate: "",
          ServiceTaxValue: "",
          ServiceSourceCurrency: "",
          ServiceCurrencyConversionRate: "",
          ServiceTargetCurrency: "",
          ServiceDetails: [
            {
              ItemName: "Gateway of India",
              ItemCategory: "10:45",
              ItemType: "INR 1500",
              ItemGrade: "INR 1200",
              ItemClass: "INR 1000",
              ItemFromDate: "",
              ItemFromTime: "",
              ItemToDate: "",
              ItemToTime: "",
              ItemUnitCost: "",
              ItemDiscount: "",
              ItemCurrency: "",
              ItemQty: "",
              ItemTotalPrice: "",
              ItemTaxValue: "",
              ItemTaxRate: "",
              ItemGrossTotalValue: "",
              ItemSupplierDeatil: {
                ItemSupplierId: "",
                ItemSupplierName: "",
                ItemSupplierRate: "",
                ItemSupplierCurrency: "",
                SupplierVoucherNumber: "",
                SupplierVoucherDate: "",
                SupplierVoucherValue: "",
                SupplierPaymentStatus: "",
              },
            },
          ],
        },
        {
          ServiceType: "Activity", // Guide/Hotel/Transport/Train/
          ServiceId: "",
          ServicePrice: "",
          ServiceTaxType: "",
          ServiceTaxRate: "",
          ServiceTaxValue: "",
          ServiceSourceCurrency: "",
          ServiceCurrencyConversionRate: "",
          ServiceTargetCurrency: "",
          ServiceDetails: [
            {
              ItemName: "Boating",
              ItemCategory: "10:45",
              ItemType: "11:45",
              ItemGrade: "INR 1200",
              ItemClass: "INR 1000",
              ItemFromDate: "10 PAX",
              ItemFromTime: "INR 1500",
              ItemToDate: "",
              ItemToTime: "",
              ItemUnitCost: "",
              ItemDiscount: "",
              ItemCurrency: "",
              ItemQty: "",
              ItemTotalPrice: "",
              ItemTaxValue: "",
              ItemTaxRate: "",
              ItemGrossTotalValue: "",
              ItemSupplierDeatil: {
                ItemSupplierId: "",
                ItemSupplierName: "",
                ItemSupplierRate: "",
                ItemSupplierCurrency: "",
                SupplierVoucherNumber: "",
                SupplierVoucherDate: "",
                SupplierVoucherValue: "",
                SupplierPaymentStatus: "",
              },
            },
          ],
        },
      ],
    },
    {
      Day: "3",
      DayUniqueId: "day_66f0fbeee646b9.04425310",
      DestiniationID: "",
      DestiniationName: "Gujarat Surat",
      DayTotal: "25 Sep | Wed",
      DayTaxValue: "",
      DayCurrencyType: "",
      DayServices: [
        {
          ServiceType: "Hotel", // Guide/Hotel/Transport/Train/
          ServiceId: "",
          ServicePrice: "",
          ServiceTaxType: "",
          ServiceTaxRate: "",
          ServiceTaxValue: "",
          ServiceSourceCurrency: "",
          ServiceCurrencyConversionRate: "",
          ServiceTargetCurrency: "",
          ServiceDetails: [
            {
              ItemName: "Ginger Surat",
              ItemCategory: "10:30",
              ItemType: "1200",
              ItemGrade: "1000",
              ItemClass: "",
              ItemFromDate: "",
              ItemFromTime: "",
              ItemToDate: "",
              ItemToTime: "",
              ItemUnitCost: "",
              ItemDiscount: "",
              ItemCurrency: "",
              ItemQty: "",
              ItemTotalPrice: "",
              ItemTaxValue: "",
              ItemTaxRate: "",
              ItemGrossTotalValue: "",
              ItemSupplierDeatil: {
                ItemSupplierId: "",
                ItemSupplierName: "",
                ItemSupplierRate: "",
                ItemSupplierCurrency: "",
                SupplierVoucherNumber: "",
                SupplierVoucherDate: "",
                SupplierVoucherValue: "",
                SupplierPaymentStatus: "",
              },
            },
          ],
        },
        {
          ServiceType: "Arrival", // Guide/Hotel/Transport/Train/
          ServiceId: "",
          ServicePrice: "",
          ServiceTaxType: "",
          ServiceTaxRate: "",
          ServiceTaxValue: "",
          ServiceSourceCurrency: "",
          ServiceCurrencyConversionRate: "",
          ServiceTargetCurrency: "",
          ServiceDetails: [
            {
              ItemName: "Vistara 13989",
              ItemCategory: "First Class",
              ItemType: "Delhi-Mumbai",
              ItemGrade: "10-10-2024",
              ItemClass: "10:15",
              ItemFromDate: "INR 1500",
              ItemFromTime: "INR 1200",
              ItemToDate: "INR 1000",
              ItemToTime: "",
              ItemUnitCost: "",
              ItemDiscount: "",
              ItemCurrency: "",
              ItemQty: "",
              ItemTotalPrice: "",
              ItemTaxValue: "",
              ItemTaxRate: "",
              ItemGrossTotalValue: "",
              ItemSupplierDeatil: {
                ItemSupplierId: "",
                ItemSupplierName: "",
                ItemSupplierRate: "",
                ItemSupplierCurrency: "",
                SupplierVoucherNumber: "",
                SupplierVoucherDate: "",
                SupplierVoucherValue: "",
                SupplierPaymentStatus: "",
              },
            },
          ],
        },
        {
          ServiceType: "Departure", // Guide/Hotel/Transport/Train/
          ServiceId: "",
          ServicePrice: "",
          ServiceTaxType: "",
          ServiceTaxRate: "",
          ServiceTaxValue: "",
          ServiceSourceCurrency: "",
          ServiceCurrencyConversionRate: "",
          ServiceTargetCurrency: "",
          ServiceDetails: [
            {
              ItemName: "Vistara 13989",
              ItemCategory: "First Class",
              ItemType: "Delhi-Mumbai",
              ItemGrade: "10-10-2024",
              ItemClass: "10:15",
              ItemFromDate: "INR 1500",
              ItemFromTime: "INR 1200",
              ItemToDate: "INR 1000",
              ItemToTime: "",
              ItemUnitCost: "",
              ItemDiscount: "",
              ItemCurrency: "",
              ItemQty: "",
              ItemTotalPrice: "",
              ItemTaxValue: "",
              ItemTaxRate: "",
              ItemGrossTotalValue: "",
              ItemSupplierDeatil: {
                ItemSupplierId: "",
                ItemSupplierName: "",
                ItemSupplierRate: "",
                ItemSupplierCurrency: "",
                SupplierVoucherNumber: "",
                SupplierVoucherDate: "",
                SupplierVoucherValue: "",
                SupplierPaymentStatus: "",
              },
            },
          ],
        },
        {
          ServiceType: "Monument", // Guide/Hotel/Transport/Train/
          ServiceId: "",
          ServicePrice: "",
          ServiceTaxType: "",
          ServiceTaxRate: "",
          ServiceTaxValue: "",
          ServiceSourceCurrency: "",
          ServiceCurrencyConversionRate: "",
          ServiceTargetCurrency: "",
          ServiceDetails: [
            {
              ItemName: "Ginger Surat",
              ItemCategory: "10:45",
              ItemType: "INR 1500",
              ItemGrade: "INR 1200",
              ItemClass: "INR 1000",
              ItemFromDate: "",
              ItemFromTime: "",
              ItemToDate: "",
              ItemToTime: "",
              ItemUnitCost: "",
              ItemDiscount: "",
              ItemCurrency: "",
              ItemQty: "",
              ItemTotalPrice: "",
              ItemTaxValue: "",
              ItemTaxRate: "",
              ItemGrossTotalValue: "",
              ItemSupplierDeatil: {
                ItemSupplierId: "",
                ItemSupplierName: "",
                ItemSupplierRate: "",
                ItemSupplierCurrency: "",
                SupplierVoucherNumber: "",
                SupplierVoucherDate: "",
                SupplierVoucherValue: "",
                SupplierPaymentStatus: "",
              },
            },
          ],
        },
        {
          ServiceType: "Activity", // Guide/Hotel/Transport/Train/
          ServiceId: "",
          ServicePrice: "",
          ServiceTaxType: "",
          ServiceTaxRate: "",
          ServiceTaxValue: "",
          ServiceSourceCurrency: "",
          ServiceCurrencyConversionRate: "",
          ServiceTargetCurrency: "",
          ServiceDetails: [
            {
              ItemName: "Visting",
              ItemCategory: "10:45",
              ItemType: "11:45",
              ItemGrade: "INR 1200",
              ItemClass: "INR 1000",
              ItemFromDate: "10 PAX",
              ItemFromTime: "INR 1500",
              ItemToDate: "",
              ItemToTime: "",
              ItemUnitCost: "",
              ItemDiscount: "",
              ItemCurrency: "",
              ItemQty: "",
              ItemTotalPrice: "",
              ItemTaxValue: "",
              ItemTaxRate: "",
              ItemGrossTotalValue: "",
              ItemSupplierDeatil: {
                ItemSupplierId: "",
                ItemSupplierName: "",
                ItemSupplierRate: "",
                ItemSupplierCurrency: "",
                SupplierVoucherNumber: "",
                SupplierVoucherDate: "",
                SupplierVoucherValue: "",
                SupplierPaymentStatus: "",
              },
            },
          ],
        },
      ],
    },
  ],
};

const quotationLabel = [
  {
    ServiceType: "Arrival",
    Label: [
      "Flight Name/Number",
      "Flight Class Name",
      "Arrival Departure",
      "Arrival Date Time",
      "Departure Date Time",
      "Adult Cost",
      "Child Cost",
    ],
  },
  {
    ServiceType: "Departure",
    Label: [
      "Flight Name/Number",
      "Flight Class Name",
      "Arrival Departure",
      "Arrival Date Time",
      "Departure Date Time",
      "Adult Cost",
      "Child Cost",
    ],
  },
  {
    ServiceType: "Monument",
    Label: ["Monument Name", "Adult Cost", "Child Cost", "Start End/Time"],
  },
  {
    ServiceType: "Hotel",
    Label: ["Hotel Name", "Service Cost", "Meal Plan", "Tariff Type"],
  },
  {
    ServiceType: "Activity",
    Label: [
      "Activity Name",
      "Pax Slab",
      "Per Pax Cost",
      "Arrival Date Time",
      "Departure Date Time",
      "Adult Cost",
      "Child Cost",
    ],
  },
];

export const itenarayInfoPopupList = {
  Status: 200,
  TotalRecord: 1,
  DataList: [
    {
      id: 1,
      FromDestination: {
        id: 16,
        Name: "Rajeev Chowk",
      },
      ToDestination: {
        id: 12,
        Name: "Red Fort Delhi",
      },
      TransferMode: "Flight",
      Title: "Sample info",
      DrivingDistance: "0",
      Details: "A non-stop flight from New York to Los Angeles.",
      Status: "1",
      AddedBy: "1",
      UpdatedBy: "1",
      CreatedAt: null,
      UpdatedAt: "2024-08-14 12:16:14",
    },
    {
      id: 2,
      FromDestination: {
        id: 16,
        Name: "Rajeev Chowk",
      },
      ToDestination: {
        id: 12,
        Name: "Red Fort Delhi",
      },
      TransferMode: "Flight",
      Title: "Sample info",
      DrivingDistance: "0",
      Details: "A non-stop flight from New York to Los Angeles.",
      Status: "1",
      AddedBy: "1",
      UpdatedBy: "1",
      CreatedAt: null,
      UpdatedAt: "2024-08-14 12:16:14",
    },
    {
      id: 3,
      FromDestination: {
        id: 16,
        Name: "Rajeev Chowk",
      },
      ToDestination: {
        id: 12,
        Name: "Red Fort Delhi",
      },
      TransferMode: "Flight",
      Title: "Sample info",
      DrivingDistance: "0",
      Details: "A non-stop flight from New York to Los Angeles.",
      Status: "1",
      AddedBy: "1",
      UpdatedBy: "1",
      CreatedAt: null,
      UpdatedAt: "2024-08-14 12:16:14",
    },
    {
      id: 4,
      FromDestination: {
        id: 16,
        Name: "Rajeev Chowk",
      },
      ToDestination: {
        id: 12,
        Name: "Red Fort Delhi",
      },
      TransferMode: "Flight",
      Title: "Sample info",
      DrivingDistance: "0",
      Details: "A non-stop flight from New York to Los Angeles.",
      Status: "1",
      AddedBy: "1",
      UpdatedBy: "1",
      CreatedAt: null,
      UpdatedAt: "2024-08-14 12:16:14",
    },
    {
      id: 5,
      FromDestination: {
        id: 16,
        Name: "Rajeev Chowk",
      },
      ToDestination: {
        id: 12,
        Name: "Red Fort Delhi",
      },
      TransferMode: "Flight",
      Title: "Sample info",
      DrivingDistance: "0",
      Details: "A non-stop flight from New York to Los Angeles.",
      Status: "1",
      AddedBy: "1",
      UpdatedBy: "1",
      CreatedAt: null,
      UpdatedAt: "2024-08-14 12:16:14",
    },
    {
      id: 6,
      FromDestination: {
        id: 16,
        Name: "Rajeev Chowk",
      },
      ToDestination: {
        id: 12,
        Name: "Red Fort Delhi",
      },
      TransferMode: "Flight",
      Title: "Sample info",
      DrivingDistance: "0",
      Details: "A non-stop flight from New York to Los Angeles.",
      Status: "1",
      AddedBy: "1",
      UpdatedBy: "1",
      CreatedAt: null,
      UpdatedAt: "2024-08-14 12:16:14",
    },
    {
      id: 7,
      FromDestination: {
        id: 16,
        Name: "Rajeev Chowk",
      },
      ToDestination: {
        id: 12,
        Name: "Red Fort Delhi",
      },
      TransferMode: "Flight",
      Title: "Sample info",
      DrivingDistance: "0",
      Details: "A non-stop flight from New York to Los Angeles.",
      Status: "1",
      AddedBy: "1",
      UpdatedBy: "1",
      CreatedAt: null,
      UpdatedAt: "2024-08-14 12:16:14",
    },
  ],
};

export const trainPopupList = {
  Status: 200,
  TotalRecord: 1,
  DataList: [
    {
      id: 2,
      Type: "B2C",
      Supplier: "MNC",
      LuxuryTrainName: "TYY",
      FixedDepartureName: "FIT",
      FixedDepartureCode: "1",
      DayWise: "Day Wise",
      Season: "Summer",
      Year: "2023",
      TotalNights: "2",
      Destination: ["Beni Mazar", "Patna", "Red Fort Delhi"],
      FromDate: "2024-08-01",
      Description: "This is a Message",
      Itinerary: [
        {
          Day: "Day 1",
          Date: "03-08-2024",
          DayOfWeek: "Sat",
          Destination: "Beni Mazar",
        },
        {
          Day: "Day 2",
          Date: "04-08-2024",
          DayOfWeek: "Sun",
          Destination: "Patna",
        },
        {
          Day: "Day 3",
          Date: "05-08-2024",
          DayOfWeek: "Mon",
          Destination: "Red Fort Delhi",
        },
      ],
      Status: "Active",
      AddedBy: 1,
      UpdatedBy: 0,
      Created_at: "2024-08-05T11:41:11.000000Z",
      Updated_at: "2024-08-05T11:41:11.000000Z",
    },
  ],
};

export const guidePopupList = {
  Status: 1,
  TotalRecords: 7,
  Data: [
    {
      Destination: "DES00010",
      ServiceType: "Guide",
      Company: "Debo000004",
      date: "2024-09-02",
      GuideServiceId: "6",
      GuideServiceUid: "GUIS0001",
      GuideServiceName: "Tester Guide",
      RateJson: {
        QuatationNo: "EST002",
        Type: "Guide",
        ServiceId: "6",
        ServiceName: "Tester Guide",
        SupplierId: "1",
        SupplierName: "Neelakshi",
        ValidFrom: "2024-09-10",
        ValidTo: "2024-09-15",
        PaxRange: "1",
        PaxRangeName: "FIT",
        DayType: "Half Day",
        UniversalCost: "No",
        GuideId: "3",
        GuideName: "Piku",
        CurrencyId: 1,
        CurrencyName: "Huyug",
        ROE: "5",
        GuideCost: "900",
        LangAllowance: "400",
        OtherCost: "800",
        GstSlabid: "8",
        GstSlabName: "AJHD",
        GstSlabValue: "10%",
        TotalCost: 2315.5,
        Status: "1",
        AddedBy: "1",
        UpdatedBy: "1",
        AddedDate: "2024-09-19",
        UpdatedDate: "2024-09-19",
      },
      Currency: 1,
      AddedBy: 1,
      RateUniqueId: "199e3701-8d60-4d78-ab56-e4360f04e035",
    },
    {
      Destination: "DES00010",
      ServiceType: "Tour Escort",
      Company: "Debo000004",
      date: "2024-09-20",
      GuideServiceId: "7",
      GuideServiceUid: "GUIS0002",
      GuideServiceName: "Night Allowance",
      RateJson: {
        ServiceId: "7",
        ServiceCost: "2000",
        TotalCost: 2000,
        CurrencyName: "Huyug",
        DestinationName: "Beni Mazar",
        CompanyName: "De-box global 3",
        LangAllowance: "",
        OtherCost: "",
        GstSlabid: "",
        GstSlabName: "",
        GstSlabValue: "",
        DayType: "Full Day",
      },
      Currency: 1,
      AddedBy: 1,
      RateUniqueId: "5caf3b5c-ee2a-44ba-903f-ac27d3b399db",
    },
    {
      Destination: "DES00010",
      ServiceType: "Tour Escort",
      Company: "Debo000004",
      date: "2024-09-20",
      GuideServiceId: "7",
      GuideServiceUid: "GUIS0002",
      GuideServiceName: "Night Allowance",
      RateJson: {
        ServiceId: "7",
        ServiceCost: "1200",
        TotalCost: 1200,
        CurrencyName: "",
        DestinationName: "Beni Mazar",
        CompanyName: "De-box global 3",
        LangAllowance: "",
        OtherCost: "",
        GstSlabid: "",
        GstSlabName: "",
        GstSlabValue: "",
        DayType: "Good Day",
      },
      Currency: 4,
      AddedBy: 1,
      RateUniqueId: "78652f7e-a856-4b1b-adad-c958817b451f",
    },
    {
      Destination: "DES00010",
      ServiceType: "Guide",
      Company: "Debo000004",
      date: "2024-09-30",
      GuideServiceId: "6",
      GuideServiceUid: "GUIS0001",
      GuideServiceName: "Tester Guide",
      RateJson: {
        QuatationNo: "EST002",
        Type: "Guide",
        ServiceId: "6",
        ServiceName: "Tester Guide",
        SupplierId: "1",
        SupplierName: "Neelakshi",
        ValidFrom: "2024-09-10",
        ValidTo: "2024-09-15",
        PaxRange: "1",
        PaxRangeName: "FIT",
        DayType: "Half Day",
        UniversalCost: "No",
        GuideId: "3",
        GuideName: "Piku",
        CurrencyId: 1,
        CurrencyName: "Huyug",
        ROE: "5",
        GuideCost: "900",
        LangAllowance: "400",
        OtherCost: "800",
        GstSlabid: "8",
        GstSlabName: "AJHD",
        GstSlabValue: "10%",
        TotalCost: 2315.5,
        Status: "1",
        AddedBy: "1",
        UpdatedBy: "1",
        AddedDate: "2024-09-19",
        UpdatedDate: "2024-09-19",
      },
      Currency: 1,
      AddedBy: 1,
      RateUniqueId: "8de3f0ca-77fa-4435-a2f3-2100e8d126cd",
    },
    {
      Destination: "DES00010",
      ServiceType: "Tour Escort",
      Company: "Debo000004",
      date: "2024-09-20",
      GuideServiceId: "7",
      GuideServiceUid: "GUIS0002",
      GuideServiceName: "Night Allowance",
      RateJson: {
        ServiceId: "7",
        ServiceCost: "2000",
        TotalCost: 2000,
        CurrencyName: "",
        DestinationName: "Beni Mazar",
        CompanyName: "De-box global 3",
        LangAllowance: "",
        OtherCost: "",
        GstSlabid: "",
        GstSlabName: "",
        GstSlabValue: "",
        DayType: "Yes Day",
      },
      Currency: 2,
      AddedBy: 1,
      RateUniqueId: "ca26fd64-b6ca-4c21-bea3-ddc58b6a663f",
    },
    {
      Destination: "DES00010",
      ServiceType: "Tour Escort",
      Company: "Debo000004",
      date: "2024-09-20",
      GuideServiceId: "7",
      GuideServiceUid: "GUIS0002",
      GuideServiceName: "Night Allowance",
      RateJson: {
        ServiceId: "7",
        ServiceCost: "2000",
        TotalCost: 2000,
        CurrencyName: "",
        DestinationName: "Beni Mazar",
        CompanyName: "De-box global 3",
        LangAllowance: "",
        OtherCost: "",
        GstSlabid: "",
        GstSlabName: "",
        GstSlabValue: "",
        DayType: "Yes Do",
      },
      Currency: 2,
      AddedBy: 1,
      RateUniqueId: "ca26fd64-b6ca-4c21-bea3-ddc58b6a663f",
    },
    {
      Destination: "DES00010",
      ServiceType: "Tour Escort",
      Company: "Debo000004",
      date: "2024-09-20",
      GuideServiceId: "7",
      GuideServiceUid: "GUIS0002",
      GuideServiceName: "Night Allowance",
      RateJson: {
        ServiceId: "7",
        ServiceCost: "2000",
        TotalCost: 2000,
        CurrencyName: "",
        DestinationName: "Beni Mazar",
        CompanyName: "De-box global 3",
        LangAllowance: "",
        OtherCost: "",
        GstSlabid: "",
        GstSlabName: "",
        GstSlabValue: "",
        DayType: "Done It",
      },
      Currency: 2,
      AddedBy: 1,
      RateUniqueId: "ca26fd64-b6ca-4c21-bea3-ddc58b6a663f",
    },
  ],
};

export const restaurantPopupList = {
  Status: 200,
  TotalRecord: 1,
  DataList: [
    {
      RateJson: {
        RestaurantId: 14,
        RestaurantUUID: "RESRED0014",
        RestaurantName: "Moonlight View",
        DestinationID: "12",
        DestinationName: "Red Fort Delhi",
        Data: [
          {
            Total: "3",
            RateDetails: [
              {
                UniqueID: "19b705fa-a0a9-47ac-867e-adf185b1a42b",
                SupplierId: "3",
                SupplierName: "Neelu",
                MealTypeId: "5",
                MealType: "Lunch",
                CurrencyId: "1",
                CurrencyName: "Huyug",
                AdultCost: "110",
                ChildCost: "50",
                GstSlabId: "4",
                GstSlabName: "Guide Tax",
                GstSlabValue: "24%",
                TotalCost: 198.4,
                Status: "1",
                AddedBy: "1",
                UpdatedBy: "1",
              },
              {
                UniqueID: "305414ab-59f2-4443-acae-f99be9d28494",
                SupplierId: "3",
                SupplierName: "Neelu",
                MealTypeId: "5",
                MealType: "Lunch",
                CurrencyId: "5",
                CurrencyName: "yen",
                AdultCost: "110",
                ChildCost: "50",
                GstSlabId: "4",
                GstSlabName: "Guide Tax",
                GstSlabValue: "24%",
                TotalCost: 198.4,
                Status: "1",
                AddedBy: "1",
                UpdatedBy: "1",
              },
              {
                UniqueID: "b06e9f40-abf7-4ec8-a02c-b8d91ac7d37d",
                SupplierId: "3",
                SupplierName: "Neelu",
                MealTypeId: "6",
                MealType: "Dinner",
                CurrencyId: "5",
                CurrencyName: "yen",
                AdultCost: "110",
                ChildCost: "50",
                GstSlabId: "4",
                GstSlabName: "Guide Tax",
                GstSlabValue: "24%",
                TotalCost: 198.4,
                Status: "1",
                AddedBy: "1",
                UpdatedBy: "1",
              },
            ],
          },
          {
            Total: "3",
            RateDetails: [
              {
                UniqueID: "19b705fa-a0a9-47ac-867e-adf185b1a42b",
                SupplierId: "3",
                SupplierName: "Neelu",
                MealTypeId: "5",
                MealType: "Lunch",
                CurrencyId: "1",
                CurrencyName: "Huyug",
                AdultCost: "110",
                ChildCost: "50",
                GstSlabId: "4",
                GstSlabName: "Guide Tax",
                GstSlabValue: "24%",
                TotalCost: 198.4,
                Status: "1",
                AddedBy: "1",
                UpdatedBy: "1",
              },
              {
                UniqueID: "305414ab-59f2-4443-acae-f99be9d28494",
                SupplierId: "3",
                SupplierName: "Neelu",
                MealTypeId: "5",
                MealType: "Lunch",
                CurrencyId: "5",
                CurrencyName: "yen",
                AdultCost: "110",
                ChildCost: "50",
                GstSlabId: "4",
                GstSlabName: "Guide Tax",
                GstSlabValue: "24%",
                TotalCost: 198.4,
                Status: "1",
                AddedBy: "1",
                UpdatedBy: "1",
              },
              {
                UniqueID: "b06e9f40-abf7-4ec8-a02c-b8d91ac7d37d",
                SupplierId: "3",
                SupplierName: "Neelu",
                MealTypeId: "6",
                MealType: "Dinner",
                CurrencyId: "5",
                CurrencyName: "yen",
                AdultCost: "110",
                ChildCost: "50",
                GstSlabId: "4",
                GstSlabName: "Guide Tax",
                GstSlabValue: "24%",
                TotalCost: 198.4,
                Status: "1",
                AddedBy: "1",
                UpdatedBy: "1",
              },
            ],
          },
        ],
      },
    },
    {
      RateJson: {
        RestaurantId: 14,
        RestaurantUUID: "RESRED0014",
        RestaurantName: "Moonlight View",
        DestinationID: "12",
        DestinationName: "Red Fort Delhi",
        Data: [
          {
            Total: "3",
            RateDetails: [
              {
                UniqueID: "19b705fa-a0a9-47ac-867e-adf185b1a42b",
                SupplierId: "3",
                SupplierName: "Neelu",
                MealTypeId: "5",
                MealType: "Lunch",
                CurrencyId: "1",
                CurrencyName: "Huyug",
                AdultCost: "110",
                ChildCost: "50",
                GstSlabId: "4",
                GstSlabName: "Guide Tax",
                GstSlabValue: "24%",
                TotalCost: 198.4,
                Status: "1",
                AddedBy: "1",
                UpdatedBy: "1",
              },
              {
                UniqueID: "305414ab-59f2-4443-acae-f99be9d28494",
                SupplierId: "3",
                SupplierName: "Neelu",
                MealTypeId: "5",
                MealType: "Lunch",
                CurrencyId: "5",
                CurrencyName: "yen",
                AdultCost: "110",
                ChildCost: "50",
                GstSlabId: "4",
                GstSlabName: "Guide Tax",
                GstSlabValue: "24%",
                TotalCost: 198.4,
                Status: "1",
                AddedBy: "1",
                UpdatedBy: "1",
              },
              {
                UniqueID: "b06e9f40-abf7-4ec8-a02c-b8d91ac7d37d",
                SupplierId: "3",
                SupplierName: "Neelu",
                MealTypeId: "6",
                MealType: "Dinner",
                CurrencyId: "5",
                CurrencyName: "yen",
                AdultCost: "110",
                ChildCost: "50",
                GstSlabId: "4",
                GstSlabName: "Guide Tax",
                GstSlabValue: "24%",
                TotalCost: 198.4,
                Status: "1",
                AddedBy: "1",
                UpdatedBy: "1",
              },
            ],
          },
          {
            Total: "3",
            RateDetails: [
              {
                UniqueID: "19b705fa-a0a9-47ac-867e-adf185b1a42b",
                SupplierId: "3",
                SupplierName: "Neelu",
                MealTypeId: "5",
                MealType: "Lunch",
                CurrencyId: "1",
                CurrencyName: "Huyug",
                AdultCost: "110",
                ChildCost: "50",
                GstSlabId: "4",
                GstSlabName: "Guide Tax",
                GstSlabValue: "24%",
                TotalCost: 198.4,
                Status: "1",
                AddedBy: "1",
                UpdatedBy: "1",
              },
              {
                UniqueID: "305414ab-59f2-4443-acae-f99be9d28494",
                SupplierId: "3",
                SupplierName: "Neelu",
                MealTypeId: "5",
                MealType: "Lunch",
                CurrencyId: "5",
                CurrencyName: "yen",
                AdultCost: "110",
                ChildCost: "50",
                GstSlabId: "4",
                GstSlabName: "Guide Tax",
                GstSlabValue: "24%",
                TotalCost: 198.4,
                Status: "1",
                AddedBy: "1",
                UpdatedBy: "1",
              },
              {
                UniqueID: "b06e9f40-abf7-4ec8-a02c-b8d91ac7d37d",
                SupplierId: "3",
                SupplierName: "Neelu",
                MealTypeId: "6",
                MealType: "Dinner",
                CurrencyId: "5",
                CurrencyName: "yen",
                AdultCost: "110",
                ChildCost: "50",
                GstSlabId: "4",
                GstSlabName: "Guide Tax",
                GstSlabValue: "24%",
                TotalCost: 198.4,
                Status: "1",
                AddedBy: "1",
                UpdatedBy: "1",
              },
            ],
          },
        ],
      },
    },
    {
      RateJson: {
        RestaurantId: 14,
        RestaurantUUID: "RESRED0014",
        RestaurantName: "Moonlight View",
        DestinationID: "12",
        DestinationName: "Red Fort Delhi",
        Data: [
          {
            Total: "3",
            RateDetails: [
              {
                UniqueID: "19b705fa-a0a9-47ac-867e-adf185b1a42b",
                SupplierId: "3",
                SupplierName: "Neelu",
                MealTypeId: "5",
                MealType: "Lunch",
                CurrencyId: "1",
                CurrencyName: "Huyug",
                AdultCost: "110",
                ChildCost: "50",
                GstSlabId: "4",
                GstSlabName: "Guide Tax",
                GstSlabValue: "24%",
                TotalCost: 198.4,
                Status: "1",
                AddedBy: "1",
                UpdatedBy: "1",
              },
              {
                UniqueID: "305414ab-59f2-4443-acae-f99be9d28494",
                SupplierId: "3",
                SupplierName: "Neelu",
                MealTypeId: "5",
                MealType: "Lunch",
                CurrencyId: "5",
                CurrencyName: "yen",
                AdultCost: "110",
                ChildCost: "50",
                GstSlabId: "4",
                GstSlabName: "Guide Tax",
                GstSlabValue: "24%",
                TotalCost: 198.4,
                Status: "1",
                AddedBy: "1",
                UpdatedBy: "1",
              },
              {
                UniqueID: "b06e9f40-abf7-4ec8-a02c-b8d91ac7d37d",
                SupplierId: "3",
                SupplierName: "Neelu",
                MealTypeId: "6",
                MealType: "Dinner",
                CurrencyId: "5",
                CurrencyName: "yen",
                AdultCost: "110",
                ChildCost: "50",
                GstSlabId: "4",
                GstSlabName: "Guide Tax",
                GstSlabValue: "24%",
                TotalCost: 198.4,
                Status: "1",
                AddedBy: "1",
                UpdatedBy: "1",
              },
            ],
          },
          {
            Total: "3",
            RateDetails: [
              {
                UniqueID: "19b705fa-a0a9-47ac-867e-adf185b1a42b",
                SupplierId: "3",
                SupplierName: "Neelu",
                MealTypeId: "5",
                MealType: "Lunch",
                CurrencyId: "1",
                CurrencyName: "Huyug",
                AdultCost: "110",
                ChildCost: "50",
                GstSlabId: "4",
                GstSlabName: "Guide Tax",
                GstSlabValue: "24%",
                TotalCost: 198.4,
                Status: "1",
                AddedBy: "1",
                UpdatedBy: "1",
              },
              {
                UniqueID: "305414ab-59f2-4443-acae-f99be9d28494",
                SupplierId: "3",
                SupplierName: "Neelu",
                MealTypeId: "5",
                MealType: "Lunch",
                CurrencyId: "5",
                CurrencyName: "yen",
                AdultCost: "110",
                ChildCost: "50",
                GstSlabId: "4",
                GstSlabName: "Guide Tax",
                GstSlabValue: "24%",
                TotalCost: 198.4,
                Status: "1",
                AddedBy: "1",
                UpdatedBy: "1",
              },
              {
                UniqueID: "b06e9f40-abf7-4ec8-a02c-b8d91ac7d37d",
                SupplierId: "3",
                SupplierName: "Neelu",
                MealTypeId: "6",
                MealType: "Dinner",
                CurrencyId: "5",
                CurrencyName: "yen",
                AdultCost: "110",
                ChildCost: "50",
                GstSlabId: "4",
                GstSlabName: "Guide Tax",
                GstSlabValue: "24%",
                TotalCost: 198.4,
                Status: "1",
                AddedBy: "1",
                UpdatedBy: "1",
              },
            ],
          },
        ],
      },
    },
    {
      RateJson: {
        RestaurantId: 14,
        RestaurantUUID: "RESRED0014",
        RestaurantName: "Moonlight View",
        DestinationID: "12",
        DestinationName: "Red Fort Delhi",
        Data: [
          {
            Total: "3",
            RateDetails: [
              {
                UniqueID: "19b705fa-a0a9-47ac-867e-adf185b1a42b",
                SupplierId: "3",
                SupplierName: "Neelu",
                MealTypeId: "5",
                MealType: "Lunch",
                CurrencyId: "1",
                CurrencyName: "Huyug",
                AdultCost: "110",
                ChildCost: "50",
                GstSlabId: "4",
                GstSlabName: "Guide Tax",
                GstSlabValue: "24%",
                TotalCost: 198.4,
                Status: "1",
                AddedBy: "1",
                UpdatedBy: "1",
              },
              {
                UniqueID: "305414ab-59f2-4443-acae-f99be9d28494",
                SupplierId: "3",
                SupplierName: "Neelu",
                MealTypeId: "5",
                MealType: "Lunch",
                CurrencyId: "5",
                CurrencyName: "yen",
                AdultCost: "110",
                ChildCost: "50",
                GstSlabId: "4",
                GstSlabName: "Guide Tax",
                GstSlabValue: "24%",
                TotalCost: 198.4,
                Status: "1",
                AddedBy: "1",
                UpdatedBy: "1",
              },
              {
                UniqueID: "b06e9f40-abf7-4ec8-a02c-b8d91ac7d37d",
                SupplierId: "3",
                SupplierName: "Neelu",
                MealTypeId: "6",
                MealType: "Dinner",
                CurrencyId: "5",
                CurrencyName: "yen",
                AdultCost: "110",
                ChildCost: "50",
                GstSlabId: "4",
                GstSlabName: "Guide Tax",
                GstSlabValue: "24%",
                TotalCost: 198.4,
                Status: "1",
                AddedBy: "1",
                UpdatedBy: "1",
              },
            ],
          },
          {
            Total: "3",
            RateDetails: [
              {
                UniqueID: "19b705fa-a0a9-47ac-867e-adf185b1a42b",
                SupplierId: "3",
                SupplierName: "Neelu",
                MealTypeId: "5",
                MealType: "Lunch",
                CurrencyId: "1",
                CurrencyName: "Huyug",
                AdultCost: "110",
                ChildCost: "50",
                GstSlabId: "4",
                GstSlabName: "Guide Tax",
                GstSlabValue: "24%",
                TotalCost: 198.4,
                Status: "1",
                AddedBy: "1",
                UpdatedBy: "1",
              },
              {
                UniqueID: "305414ab-59f2-4443-acae-f99be9d28494",
                SupplierId: "3",
                SupplierName: "Neelu",
                MealTypeId: "5",
                MealType: "Lunch",
                CurrencyId: "5",
                CurrencyName: "yen",
                AdultCost: "110",
                ChildCost: "50",
                GstSlabId: "4",
                GstSlabName: "Guide Tax",
                GstSlabValue: "24%",
                TotalCost: 198.4,
                Status: "1",
                AddedBy: "1",
                UpdatedBy: "1",
              },
              {
                UniqueID: "b06e9f40-abf7-4ec8-a02c-b8d91ac7d37d",
                SupplierId: "3",
                SupplierName: "Neelu",
                MealTypeId: "6",
                MealType: "Dinner",
                CurrencyId: "5",
                CurrencyName: "yen",
                AdultCost: "110",
                ChildCost: "50",
                GstSlabId: "4",
                GstSlabName: "Guide Tax",
                GstSlabValue: "24%",
                TotalCost: 198.4,
                Status: "1",
                AddedBy: "1",
                UpdatedBy: "1",
              },
            ],
          },
        ],
      },
    },
    {
      RateJson: {
        RestaurantId: 14,
        RestaurantUUID: "RESRED0014",
        RestaurantName: "Moonlight View",
        DestinationID: "12",
        DestinationName: "Red Fort Delhi",
        Data: [
          {
            Total: "3",
            RateDetails: [
              {
                UniqueID: "19b705fa-a0a9-47ac-867e-adf185b1a42b",
                SupplierId: "3",
                SupplierName: "Neelu",
                MealTypeId: "5",
                MealType: "Lunch",
                CurrencyId: "1",
                CurrencyName: "Huyug",
                AdultCost: "110",
                ChildCost: "50",
                GstSlabId: "4",
                GstSlabName: "Guide Tax",
                GstSlabValue: "24%",
                TotalCost: 198.4,
                Status: "1",
                AddedBy: "1",
                UpdatedBy: "1",
              },
              {
                UniqueID: "305414ab-59f2-4443-acae-f99be9d28494",
                SupplierId: "3",
                SupplierName: "Neelu",
                MealTypeId: "5",
                MealType: "Lunch",
                CurrencyId: "5",
                CurrencyName: "yen",
                AdultCost: "110",
                ChildCost: "50",
                GstSlabId: "4",
                GstSlabName: "Guide Tax",
                GstSlabValue: "24%",
                TotalCost: 198.4,
                Status: "1",
                AddedBy: "1",
                UpdatedBy: "1",
              },
              {
                UniqueID: "b06e9f40-abf7-4ec8-a02c-b8d91ac7d37d",
                SupplierId: "3",
                SupplierName: "Neelu",
                MealTypeId: "6",
                MealType: "Dinner",
                CurrencyId: "5",
                CurrencyName: "yen",
                AdultCost: "110",
                ChildCost: "50",
                GstSlabId: "4",
                GstSlabName: "Guide Tax",
                GstSlabValue: "24%",
                TotalCost: 198.4,
                Status: "1",
                AddedBy: "1",
                UpdatedBy: "1",
              },
            ],
          },
          {
            Total: "3",
            RateDetails: [
              {
                UniqueID: "19b705fa-a0a9-47ac-867e-adf185b1a42b",
                SupplierId: "3",
                SupplierName: "Neelu",
                MealTypeId: "5",
                MealType: "Lunch",
                CurrencyId: "1",
                CurrencyName: "Huyug",
                AdultCost: "110",
                ChildCost: "50",
                GstSlabId: "4",
                GstSlabName: "Guide Tax",
                GstSlabValue: "24%",
                TotalCost: 198.4,
                Status: "1",
                AddedBy: "1",
                UpdatedBy: "1",
              },
              {
                UniqueID: "305414ab-59f2-4443-acae-f99be9d28494",
                SupplierId: "3",
                SupplierName: "Neelu",
                MealTypeId: "5",
                MealType: "Lunch",
                CurrencyId: "5",
                CurrencyName: "yen",
                AdultCost: "110",
                ChildCost: "50",
                GstSlabId: "4",
                GstSlabName: "Guide Tax",
                GstSlabValue: "24%",
                TotalCost: 198.4,
                Status: "1",
                AddedBy: "1",
                UpdatedBy: "1",
              },
              {
                UniqueID: "b06e9f40-abf7-4ec8-a02c-b8d91ac7d37d",
                SupplierId: "3",
                SupplierName: "Neelu",
                MealTypeId: "6",
                MealType: "Dinner",
                CurrencyId: "5",
                CurrencyName: "yen",
                AdultCost: "110",
                ChildCost: "50",
                GstSlabId: "4",
                GstSlabName: "Guide Tax",
                GstSlabValue: "24%",
                TotalCost: 198.4,
                Status: "1",
                AddedBy: "1",
                UpdatedBy: "1",
              },
            ],
          },
        ],
      },
    },
    {
      RateJson: {
        RestaurantId: 14,
        RestaurantUUID: "RESRED0014",
        RestaurantName: "Moonlight View",
        DestinationID: "12",
        DestinationName: "Red Fort Delhi",
        Data: [
          {
            Total: "3",
            RateDetails: [
              {
                UniqueID: "19b705fa-a0a9-47ac-867e-adf185b1a42b",
                SupplierId: "3",
                SupplierName: "Neelu",
                MealTypeId: "5",
                MealType: "Lunch",
                CurrencyId: "1",
                CurrencyName: "Huyug",
                AdultCost: "110",
                ChildCost: "50",
                GstSlabId: "4",
                GstSlabName: "Guide Tax",
                GstSlabValue: "24%",
                TotalCost: 198.4,
                Status: "1",
                AddedBy: "1",
                UpdatedBy: "1",
              },
              {
                UniqueID: "305414ab-59f2-4443-acae-f99be9d28494",
                SupplierId: "3",
                SupplierName: "Neelu",
                MealTypeId: "5",
                MealType: "Lunch",
                CurrencyId: "5",
                CurrencyName: "yen",
                AdultCost: "110",
                ChildCost: "50",
                GstSlabId: "4",
                GstSlabName: "Guide Tax",
                GstSlabValue: "24%",
                TotalCost: 198.4,
                Status: "1",
                AddedBy: "1",
                UpdatedBy: "1",
              },
              {
                UniqueID: "b06e9f40-abf7-4ec8-a02c-b8d91ac7d37d",
                SupplierId: "3",
                SupplierName: "Neelu",
                MealTypeId: "6",
                MealType: "Dinner",
                CurrencyId: "5",
                CurrencyName: "yen",
                AdultCost: "110",
                ChildCost: "50",
                GstSlabId: "4",
                GstSlabName: "Guide Tax",
                GstSlabValue: "24%",
                TotalCost: 198.4,
                Status: "1",
                AddedBy: "1",
                UpdatedBy: "1",
              },
            ],
          },
          {
            Total: "3",
            RateDetails: [
              {
                UniqueID: "19b705fa-a0a9-47ac-867e-adf185b1a42b",
                SupplierId: "3",
                SupplierName: "Neelu",
                MealTypeId: "5",
                MealType: "Lunch",
                CurrencyId: "1",
                CurrencyName: "Huyug",
                AdultCost: "110",
                ChildCost: "50",
                GstSlabId: "4",
                GstSlabName: "Guide Tax",
                GstSlabValue: "24%",
                TotalCost: 198.4,
                Status: "1",
                AddedBy: "1",
                UpdatedBy: "1",
              },
              {
                UniqueID: "305414ab-59f2-4443-acae-f99be9d28494",
                SupplierId: "3",
                SupplierName: "Neelu",
                MealTypeId: "5",
                MealType: "Lunch",
                CurrencyId: "5",
                CurrencyName: "yen",
                AdultCost: "110",
                ChildCost: "50",
                GstSlabId: "4",
                GstSlabName: "Guide Tax",
                GstSlabValue: "24%",
                TotalCost: 198.4,
                Status: "1",
                AddedBy: "1",
                UpdatedBy: "1",
              },
              {
                UniqueID: "b06e9f40-abf7-4ec8-a02c-b8d91ac7d37d",
                SupplierId: "3",
                SupplierName: "Neelu",
                MealTypeId: "6",
                MealType: "Dinner",
                CurrencyId: "5",
                CurrencyName: "yen",
                AdultCost: "110",
                ChildCost: "50",
                GstSlabId: "4",
                GstSlabName: "Guide Tax",
                GstSlabValue: "24%",
                TotalCost: 198.4,
                Status: "1",
                AddedBy: "1",
                UpdatedBy: "1",
              },
            ],
          },
        ],
      },
    },
  ],
};

const transport = {
  Status: 200,
  TotalRecord: 1,
  DataList: [
    {
      TransportUID: "TPTHYD0016",
      Destination: {
        id: "DES0001",
        Name: "Agra",
      },
      Date: "2026-02-07",
      SupplierUID: {
        id: "SUPP0001",
        Name: "Test",
      },
      CompanyId: {
        id: "COMP0001",
        Name: "De-box",
      },
      Currency: {
        id: "1",
        Name: "Huyug",
      },
      RateJson: null,
      Status: 1,
      AddedBy: 1,
      UpdatedBy: 1,
      CreatedAt: null,
      UpdatedAt: null,
    },
  ],
};

export const monumentPopupList = {
  Status: 200,
  TotalRecord: 1,
  DataList: [
    {
      MonumentUID: "MONPAT0006",
      MonumentName: "Taj Mahal",
      Destination: {
        id: "DES0001",
        Name: "Agra",
      },
      Date: "2024-05-18",
      SupplierUID: {
        id: "SUPP0001",
        Name: "Test",
      },
      CompanyID: {
        id: "COMP0001",
        Name: "De-box",
      },
      Currency: {
        id: "5",
        Name: "yen",
      },
      RateJson: {
        MonumentId: 9,
        AdultEntFee: 150,
        ChildEntFee: 50,
        TaxSlabId: 4,
        TaxSlabName: "Guide Tax",
        TaxSlabVal: "24%",
        TotalCost: 248,
        CurrencyName: "yen",
        DestinationName: "Agra",
        CompanyName: "De-box",
        NationalityName: "Neelakshi",
      },
      Status: 1,
      AddedBy: 1,
      UpdatedBy: 1,
      CreatedAt: null,
      UpdatedAt: null,
    },
    {
      MonumentUID: "MONPAT0006",
      MonumentName: "Taj Mahal",
      Destination: {
        id: "DES0001",
        Name: "Agra",
      },
      Date: "2024-05-18",
      SupplierUID: {
        id: "SUPP0001",
        Name: "Test",
      },
      CompanyID: {
        id: "COMP0001",
        Name: "De-box",
      },
      Currency: {
        id: "5",
        Name: "yen",
      },
      RateJson: {
        MonumentId: 9,
        AdultEntFee: 150,
        ChildEntFee: 50,
        TaxSlabId: 4,
        TaxSlabName: "Guide Tax",
        TaxSlabVal: "24%",
        TotalCost: 248,
        CurrencyName: "yen",
        DestinationName: "Agra",
        CompanyName: "De-box",
        NationalityName: "Neelakshi",
      },
      Status: 1,
      AddedBy: 1,
      UpdatedBy: 1,
      CreatedAt: null,
      UpdatedAt: null,
    },
    {
      MonumentUID: "MONPAT0006",
      MonumentName: "Taj Mahal",
      Destination: {
        id: "DES0001",
        Name: "Agra",
      },
      Date: "2024-05-18",
      SupplierUID: {
        id: "SUPP0001",
        Name: "Test",
      },
      CompanyID: {
        id: "COMP0001",
        Name: "De-box",
      },
      Currency: {
        id: "5",
        Name: "yen",
      },
      RateJson: {
        MonumentId: 9,
        AdultEntFee: 150,
        ChildEntFee: 50,
        TaxSlabId: 4,
        TaxSlabName: "Guide Tax",
        TaxSlabVal: "24%",
        TotalCost: 248,
        CurrencyName: "yen",
        DestinationName: "Agra",
        CompanyName: "De-box",
        NationalityName: "Neelakshi",
      },
      Status: 1,
      AddedBy: 1,
      UpdatedBy: 1,
      CreatedAt: null,
      UpdatedAt: null,
    },
    {
      MonumentUID: "MONPAT0006",
      MonumentName: "Taj Mahal",
      Destination: {
        id: "DES0001",
        Name: "Agra",
      },
      Date: "2024-05-18",
      SupplierUID: {
        id: "SUPP0001",
        Name: "Test",
      },
      CompanyID: {
        id: "COMP0001",
        Name: "De-box",
      },
      Currency: {
        id: "5",
        Name: "yen",
      },
      RateJson: {
        MonumentId: 9,
        AdultEntFee: 150,
        ChildEntFee: 50,
        TaxSlabId: 4,
        TaxSlabName: "Guide Tax",
        TaxSlabVal: "24%",
        TotalCost: 248,
        CurrencyName: "yen",
        DestinationName: "Agra",
        CompanyName: "De-box",
        NationalityName: "Neelakshi",
      },
      Status: 1,
      AddedBy: 1,
      UpdatedBy: 1,
      CreatedAt: null,
      UpdatedAt: null,
    },
    {
      MonumentUID: "MONPAT0006",
      MonumentName: "Taj Mahal",
      Destination: {
        id: "DES0001",
        Name: "Agra",
      },
      Date: "2024-05-18",
      SupplierUID: {
        id: "SUPP0001",
        Name: "Test",
      },
      CompanyID: {
        id: "COMP0001",
        Name: "De-box",
      },
      Currency: {
        id: "5",
        Name: "yen",
      },
      RateJson: {
        MonumentId: 9,
        AdultEntFee: 150,
        ChildEntFee: 50,
        TaxSlabId: 4,
        TaxSlabName: "Guide Tax",
        TaxSlabVal: "24%",
        TotalCost: 248,
        CurrencyName: "yen",
        DestinationName: "Agra",
        CompanyName: "De-box",
        NationalityName: "Neelakshi",
      },
      Status: 1,
      AddedBy: 1,
      UpdatedBy: 1,
      CreatedAt: null,
      UpdatedAt: null,
    },
    {
      MonumentUID: "MONPAT0006",
      MonumentName: "Taj Mahal",
      Destination: {
        id: "DES0001",
        Name: "Agra",
      },
      Date: "2024-05-18",
      SupplierUID: {
        id: "SUPP0001",
        Name: "Test",
      },
      CompanyID: {
        id: "COMP0001",
        Name: "De-box",
      },
      Currency: {
        id: "5",
        Name: "yen",
      },
      RateJson: {
        MonumentId: 9,
        AdultEntFee: 150,
        ChildEntFee: 50,
        TaxSlabId: 4,
        TaxSlabName: "Guide Tax",
        TaxSlabVal: "24%",
        TotalCost: 248,
        CurrencyName: "yen",
        DestinationName: "Agra",
        CompanyName: "De-box",
        NationalityName: "Neelakshi",
      },
      Status: 1,
      AddedBy: 1,
      UpdatedBy: 1,
      CreatedAt: null,
      UpdatedAt: null,
    }
  ],
};

export default data;
export { quotationData, quotationLabel };
